(function(){var aa="_imgFileNameError",ca="_imgUrlTextError",da="allHolder",ea="aria-expanded",fa="bgresponse",ha="chooseWidget",ia="commentBodyField",e="complete",ja="displayModeLayout",ka="displayModeNone",h="div",la="encodedSelectedId",m="function",ma="genericOpenIdIdentityHolder",na="goog-zippy-collapsed",oa="goog-zippy-expanded",pa="hidden",qa="identity-type-",ra="identityHolder",sa="identityMenu",ta="input",ua="keypress",va="layout-widget-description",wa="layout-widget-title",xa="main-status-holder",ya=
"nameUrlIdentityHolder",n="none",za="number",Aa="object",Ba="openIdIdentityHolder",Ca="openIdUriField",Da="openIdUserNameField",Ea="postCommentSubmit",Fa="ready",Ga="rotate(-45deg)",Ha="sectionWidth",Ia="select-multiple",Ja="showPreview",Ka="status-message",La="status-message-inner",Ma="subscribeButtonHolder",Na="success",Oa="true",p,Pa=typeof Object.defineProperties==m?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},Qa="undefined"!=typeof window&&window===
this?this:"undefined"!=typeof global&&null!=global?global:this,Ra=function(){Ra=function(){};Qa.Symbol||(Qa.Symbol=Sa)},Sa=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),Ua=function(){Ra();var a=Qa.Symbol.iterator;a||(a=Qa.Symbol.iterator=Qa.Symbol("iterator"));typeof Array.prototype[a]!=m&&Pa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Ta(this)}});Ua=function(){}},Ta=function(a){var b=0;return Va(function(){return b<a.length?{done:!1,value:a[b++]}:
{done:!0}})},Va=function(a){Ua();a={next:a};a[Qa.Symbol.iterator]=function(){return this};return a},Wa=Wa||{},r=this,t=function(a){return void 0!==a},u=function(a){return"string"==typeof a},Xa=function(a){return typeof a==za},v=function(a,b,c){a=a.split(".");c=c||r;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&t(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}},Ya=function(){},Za=function(a){a.zc=void 0;a.qg=function(){return a.zc?a.zc:a.zc=
new a}},$a=function(a){var b=typeof a;if(b==Aa)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return Aa;if("[object Array]"==c||typeof a.length==za&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return m}else return"null";
else if(b==m&&"undefined"==typeof a.call)return Aa;return b},w=function(a){return"array"==$a(a)},ab=function(a){var b=$a(a);return"array"==b||b==Aa&&typeof a.length==za},bb=function(a){return $a(a)==m},cb=function(a){var b=typeof a;return b==Aa&&null!=a||b==m},db="closure_uid_"+(1E9*Math.random()>>>0),eb=0,fb=function(a,b,c){return a.call.apply(a.bind,arguments)},gb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);
Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fb:gb;return x.apply(null,arguments)},hb=Date.now||function(){return+new Date},y=function(a,b){function c(){}c.prototype=b.prototype;a.h=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Uh=function(a,c,g){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];
return b.prototype[c].apply(a,d)}};var ib;var jb=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")},kb=function(a){return a.replace(/\xa0|[ \t]+/g," ")},lb=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},tb=function(a,b){if(b)a=a.replace(mb,"&amp;").replace(nb,"&lt;").replace(ob,"&gt;").replace(pb,"&quot;").replace(qb,"&#39;").replace(rb,"&#0;");else{if(!sb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(mb,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(nb,"&lt;"));-1!=a.indexOf(">")&&
(a=a.replace(ob,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(pb,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(qb,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(rb,"&#0;"))}return a},mb=/&/g,nb=/</g,ob=/>/g,pb=/"/g,qb=/'/g,rb=/\x00/g,sb=/[\x00&<>"']/,z=function(a,b){return-1!=a.indexOf(b)},ub=function(a,b){return a<b?-1:a>b?1:0};var vb=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(u(a))return u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},wb=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(u(a))return u(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=
c;c--)if(c in a&&a[c]===b)return c;return-1},xb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},yb=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,k=u(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var q=k[l];b.call(c,q,l,a)&&(f[g++]=q)}return f},Ab=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,
b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=u(a)?a.split(""):a,k=0;k<d;k++)k in g&&(f[k]=b.call(c,g[k],k,a));return f},Bb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1},Cb=function(a,b,c){a:{for(var d=a.length,f=u(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a)){b=g;break a}b=-1}return 0>b?null:u(a)?a.charAt(b):a[b]},A=function(a,
b){return 0<=vb(a,b)},Db=function(a){if(!w(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0},Eb=function(a,b){b=vb(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},Fb=function(a){return Array.prototype.concat.apply([],arguments)},Gb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Hb=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var B;a:{var Ib=r.navigator;if(Ib){var Jb=Ib.userAgent;if(Jb){B=Jb;break a}}B=""};var Kb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Lb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Mb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Nb=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1},Ob=function(a){for(var b in a)return!1;return!0},Pb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Qb=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=
0;g<Pb.length;g++)c=Pb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Rb=function(a){var b=arguments.length;if(1==b&&w(arguments[0]))return Rb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var Sb=function(a){Sb[" "](a);return a};Sb[" "]=Ya;var Tb=function(a,b,c,d){d=d?d(b):b;return Object.prototype.hasOwnProperty.call(a,d)?a[d]:a[d]=c(b)};var Ub=z(B,"Opera"),C=z(B,"Trident")||z(B,"MSIE"),D=z(B,"Edge"),E=z(B,"Gecko")&&!(z(B.toLowerCase(),"webkit")&&!z(B,"Edge"))&&!(z(B,"Trident")||z(B,"MSIE"))&&!z(B,"Edge"),F=z(B.toLowerCase(),"webkit")&&!z(B,"Edge"),G=z(B,"Macintosh"),Vb=function(){var a=r.document;return a?a.documentMode:void 0},Wb;
a:{var Xb="",Yb=function(){var a=B;if(E)return/rv\:([^\);]+)(\)|;)/.exec(a);if(D)return/Edge\/([\d\.]+)/.exec(a);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(F)return/WebKit\/(\S+)/.exec(a);if(Ub)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Yb&&(Xb=Yb?Yb[1]:"");if(C){var Zb=Vb();if(null!=Zb&&Zb>parseFloat(Xb)){Wb=String(Zb);break a}}Wb=Xb}
var $b=Wb,ac={},H=function(a){return Tb(ac,a,function(){for(var b=0,c=lb(String($b)).split("."),d=lb(String(a)).split("."),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var k=c[g]||"",l=d[g]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=ub(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||ub(0==k[2].length,0==l[2].length)||ub(k[2],l[2]);k=k[3];l=l[3]}while(0==b)}return 0<=b})},bc;
var cc=r.document;bc=cc&&C?Vb()||("CSS1Compat"==cc.compatMode?parseInt($b,10):5):void 0;var dc=!C||9<=Number(bc);!E&&!C||C&&9<=Number(bc)||E&&H("1.9.1");C&&H("9");var fc=function(){this.Xc="";this.Af=ec};fc.prototype.Wa=!0;fc.prototype.Ba=function(){return this.Xc};fc.prototype.toString=function(){return"Const{"+this.Xc+"}"};var ec={};var hc=function(){this.Oc="";this.zf=gc};hc.prototype.Wa=!0;hc.prototype.Ba=function(){return this.Oc};var ic=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,kc=function(a){if(a instanceof hc)return a;a=a.Wa?a.Ba():String(a);ic.test(a)||(a="about:invalid#zClosurez");return jc(a)},gc={},jc=function(a){var b=new hc;b.Oc=a;return b};jc("about:blank");var I=function(){this.Qc="";this.yf=lc};I.prototype.Wa=!0;var lc={};I.prototype.Ba=function(){return this.Qc};I.prototype.Ya=function(a){this.Qc=a;return this};
var mc=(new I).Ya(""),rc=function(a){if(a instanceof fc)return a instanceof fc&&a.constructor===fc&&a.Af===ec?a.Xc:"type_error:Const";if(a instanceof hc)return a instanceof hc&&a.constructor===hc&&a.zf===gc?a=a.Oc:($a(a),a="type_error:SafeUrl"),'url("'+a.replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';a=String(a);var b=a.replace(nc,"$1").replace(oc,"url");if(b=pc.test(b)){for(var c=b=!0,d=0;d<a.length;d++){var f=a.charAt(d);"'"==f&&c?b=!b:'"'==f&&b&&(c=!c)}b=b&&c}return b?qc(a):"zClosurez"},pc=
/^[-,."'%_!# a-zA-Z0-9]+$/,oc=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,nc=/\b(hsl|hsla|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?)\([-0-9a-z.%, ]+\)/g,qc=function(a){return a.replace(oc,function(a,c,d,f){var b="";d=d.replace(/^(['"])(.*)\1$/,function(a,c,d){b=c;return d});a=kc(d).Ba();return c+b+a+b+f})};var tc=function(){this.Pc="";this.xf=sc};tc.prototype.Wa=!0;
var sc={},uc=function(a,b){if(z(a,"<"))throw Error("Selector does not allow '<', got: "+a);var c=a.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(c))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+a);a:{for(var d={"(":")","[":"]"},f=[],g=0;g<c.length;g++){var k=c[g];if(d[k])f.push(d[k]);else if(Nb(d,k)&&f.pop()!=k){c=!1;break a}}c=0==f.length}if(!c)throw Error("() and [] in selector must be balanced, got: "+a);
if(!(b instanceof I)){c="";for(var l in b){if(!/^[-_a-zA-Z0-9]+$/.test(l))throw Error("Name allows only [-_a-zA-Z0-9], got: "+l);d=b[l];null!=d&&(d=w(d)?Ab(d,rc).join(" "):rc(d),c+=l+":"+d+";")}b=c?(new I).Ya(c):mc}b instanceof I&&b.constructor===I&&b.yf===lc?l=b.Qc:($a(b),l="type_error:SafeStyle");return(new tc).Ya(a+"{"+l+"}")},wc=function(a){var b="",c=function(a){w(a)?xb(a,c):b+=vc(a)};xb(arguments,c);return(new tc).Ya(b)};tc.prototype.Ba=function(){return this.Pc};
var vc=function(a){if(a instanceof tc&&a.constructor===tc&&a.xf===sc)return a.Pc;$a(a);return"type_error:SafeStyleSheet"};tc.prototype.Ya=function(a){this.Pc=a;return this};var xc=function(a,b){this.width=a;this.height=b};xc.prototype.clone=function(){return new xc(this.width,this.height)};xc.prototype.Vf=function(){return this.width*this.height};xc.prototype.isEmpty=function(){return!this.Vf()};xc.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var zc=function(a){return a?new yc(9==a.nodeType?a:a.ownerDocument||a.document):ib||(ib=new yc)},J=function(a){return u(a)?document.getElementById(a):a},Bc=function(a,b){Kb(b,function(b,d){b&&b.Wa&&(b=b.Ba());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Ac.hasOwnProperty(d)?a.setAttribute(Ac[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Ac={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",
height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Dc=function(a,b,c){return Cc(document,arguments)},Cc=function(a,b){var c=String(b[0]),d=b[1];if(!dc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',tb(d.name),'"');if(d.type){c.push(' type="',tb(d.type),'"');var f={};Qb(f,d);delete f.type;d=f}c.push(">");c=c.join("")}c=a.createElement(c);d&&(u(d)?c.className=d:w(d)?c.className=d.join(" "):Bc(c,d));2<
b.length&&Ec(a,c,b,2);return c},Ec=function(a,b,c,d){function f(c){c&&b.appendChild(u(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!ab(g)||cb(g)&&0<g.nodeType?f(g):xb(Fc(g)?Gb(g):g,f)}},Gc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},Fc=function(a){if(a&&typeof a.length==za){if(cb(a))return typeof a.item==m||"string"==typeof a.item;if(bb(a))return typeof a.item==m}return!1},yc=function(a){this.oa=a||r.document||document};p=yc.prototype;
p.Ra=function(a){return u(a)?this.oa.getElementById(a):a};p.getElementsByTagName=function(a,b){return(b||this.oa).getElementsByTagName(String(a))};
p.Md=function(a,b,c){c=c||this.oa;var d=a&&"*"!=a?String(a).toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(d||b))b=c.querySelectorAll(d+(b?"."+b:""));else if(b&&c.getElementsByClassName){var f=c.getElementsByClassName(b);if(d){c={};for(var g=a=0,k;k=f[g];g++)d==k.nodeName&&(c[a++]=k);c.length=a;b=c}else b=f}else if(f=c.getElementsByTagName(d||"*"),b){c={};for(g=a=0;k=f[g];g++)d=k.className,typeof d.split==m&&A(d.split(/\s+/),b)&&(c[a++]=k);c.length=a;b=c}else b=f;return b};
p.mc=function(a,b,c){return Cc(this.oa,arguments)};p.createElement=function(a){return this.oa.createElement(String(a))};p.createTextNode=function(a){return this.oa.createTextNode(String(a))};p.appendChild=function(a,b){a.appendChild(b)};p.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var Hc=function(a){return a};var K=function(){this.wa=this.wa;this.Pb=this.Pb};K.prototype.wa=!1;K.prototype.na=function(){this.wa||(this.wa=!0,this.i())};K.prototype.i=function(){if(this.Pb)for(;this.Pb.length;)this.Pb.shift()()};var Ic=function(a){a&&typeof a.na==m&&a.na()};var Jc=!C||9<=Number(bc),Kc=C&&!H("9");!F||H("528");E&&H("1.9b")||C&&H("8")||Ub&&H("9.5")||F&&H("528");E&&!H("8")||C&&H("9");var Lc=function(){if(!r.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});r.addEventListener("test",Ya,b);r.removeEventListener("test",Ya,b);return a}();var L=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.ta=!1;this.Ee=!0};L.prototype.stopPropagation=function(){this.ta=!0};L.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Ee=!1};var N=function(a,b){L.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.ya=this.state=null;a&&this.Zd(a,b)};y(N,L);
N.prototype.Zd=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(E){a:{try{Sb(b.nodeName);var f=!0;break a}catch(g){}f=!1}f||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.offsetX=F||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=F||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,
this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||(c==ua?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.ya=a;a.defaultPrevented&&
this.preventDefault()};N.prototype.stopPropagation=function(){N.h.stopPropagation.call(this);this.ya.stopPropagation?this.ya.stopPropagation():this.ya.cancelBubble=!0};N.prototype.preventDefault=function(){N.h.preventDefault.call(this);var a=this.ya;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Kc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Mc="closure_listenable_"+(1E6*Math.random()|0),Nc=function(a){return!(!a||!a[Mc])},Oc=0;var Pc=function(a,b,c,d,f,g){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!f;this.Bb=g;this.key=++Oc;this.Ha=this.qb=!1};Pc.prototype.Nb=function(){this.Ha=!0;this.Bb=this.src=this.proxy=this.listener=null};var Qc=function(a){this.src=a;this.o={};this.kb=0};p=Qc.prototype;p.add=function(a,b,c,d,f){var g=a.toString();a=this.o[g];a||(a=this.o[g]=[],this.kb++);var k=Rc(a,b,d,f);-1<k?(b=a[k],c||(b.qb=!1)):(b=new Pc(b,null,this.src,g,!!d,f),b.qb=c,a.push(b));return b};p.remove=function(a,b,c,d){a=a.toString();if(!(a in this.o))return!1;var f=this.o[a];b=Rc(f,b,c,d);return-1<b?(f[b].Nb(),Array.prototype.splice.call(f,b,1),0==f.length&&(delete this.o[a],this.kb--),!0):!1};
p.ze=function(a){var b=a.type;if(!(b in this.o))return!1;var c=Eb(this.o[b],a);c&&(a.Nb(),0==this.o[b].length&&(delete this.o[b],this.kb--));return c};p.Rb=function(a){a=a&&a.toString();var b=0,c;for(c in this.o)if(!a||c==a){for(var d=this.o[c],f=0;f<d.length;f++)++b,d[f].Nb();delete this.o[c];this.kb--}return b};p.Sa=function(a,b,c,d){a=this.o[a.toString()];var f=-1;a&&(f=Rc(a,b,c,d));return-1<f?a[f]:null};
var Rc=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.Ha&&g.listener==b&&g.capture==!!c&&g.Bb==d)return f}return-1};var Sc="closure_lm_"+(1E6*Math.random()|0),Tc={},Uc=0,O=function(a,b,c,d,f){if(d&&d.once)return Vc(a,b,c,d,f);if(w(b)){for(var g=0;g<b.length;g++)O(a,b[g],c,d,f);return null}c=Wc(c);return Nc(a)?a.Ga(b,c,cb(d)?!!d.capture:!!d,f):Xc(a,b,c,!1,d,f)},Xc=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var k=cb(f)?!!f.capture:!!f,l=Yc(a);l||(a[Sc]=l=new Qc(a));c=l.add(b,c,d,k,g);if(c.proxy)return c;d=Zc();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Lc||(f=k),void 0===f&&(f=!1),a.addEventListener(b.toString(),
d,f);else if(a.attachEvent)a.attachEvent($c(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");Uc++;return c},Zc=function(){var a=ad,b=Jc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Vc=function(a,b,c,d,f){if(w(b)){for(var g=0;g<b.length;g++)Vc(a,b[g],c,d,f);return null}c=Wc(c);return Nc(a)?a.Ec(b,c,cb(d)?!!d.capture:!!d,f):Xc(a,b,c,!0,d,f)},bd=function(a,b,c,d,f){if(w(b)){for(var g=0;g<b.length;g++)bd(a,
b[g],c,d,f);return null}d=cb(d)?!!d.capture:!!d;c=Wc(c);if(Nc(a))return a.Wb(b,c,d,f);if(!a)return!1;if(a=Yc(a))if(b=a.Sa(b,c,d,f))return cd(b);return!1},cd=function(a){if(Xa(a)||!a||a.Ha)return!1;var b=a.src;if(Nc(b))return b.We(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent($c(c),d);Uc--;(c=Yc(b))?(c.ze(a),0==c.kb&&(c.src=null,b[Sc]=null)):a.Nb();return!0},dd=function(a,b){if(!a)return 0;if(Nc(a))return a.ye(b);a=Yc(a);if(!a)return 0;
var c=0;b=b&&b.toString();for(var d in a.o)if(!b||d==b)for(var f=a.o[d].concat(),g=0;g<f.length;++g)cd(f[g])&&++c;return c},$c=function(a){return a in Tc?Tc[a]:Tc[a]="on"+a},fd=function(a,b,c,d){var f=!0;if(a=Yc(a))if(b=a.o[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.Ha&&(g=ed(g,d),f=f&&!1!==g)}return f},ed=function(a,b){var c=a.listener,d=a.Bb||a.src;a.qb&&cd(a);return c.call(d,b)},ad=function(a,b){if(a.Ha)return!0;if(!Jc){if(!b)a:{b=["window","event"];for(var c=
r,d;d=b.shift();)if(null!=c[d])c=c[d];else{b=null;break a}b=c}d=b;b=new N(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var f=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(k){f=!0}if(f||void 0==d.returnValue)d.returnValue=!0}d=[];for(f=b.currentTarget;f;f=f.parentNode)d.push(f);f=a.type;for(var g=d.length-1;!b.ta&&0<=g;g--)b.currentTarget=d[g],a=fd(d[g],f,!0,b),c=c&&a;for(g=0;!b.ta&&g<d.length;g++)b.currentTarget=d[g],a=fd(d[g],f,!1,b),c=c&&a}return c}return ed(a,new N(b,this))},Yc=
function(a){a=a[Sc];return a instanceof Qc?a:null},gd="__closure_events_fn_"+(1E9*Math.random()>>>0),Wc=function(a){if(bb(a))return a;a[gd]||(a[gd]=function(b){return a.handleEvent(b)});return a[gd]};var P=function(){K.call(this);this.fa=new Qc(this);this.Of=this;this.Lc=null};y(P,K);P.prototype[Mc]=!0;p=P.prototype;p.addEventListener=function(a,b,c,d){O(this,a,b,c,d)};p.removeEventListener=function(a,b,c,d){bd(this,a,b,c,d)};
p.dispatchEvent=function(a){var b=this.Lc;if(b){var c=[];for(var d=1;b;b=b.Lc)c.push(b),++d}b=this.Of;d=a.type||a;if(u(a))a=new L(a,b);else if(a instanceof L)a.target=a.target||b;else{var f=a;a=new L(d,b);Qb(a,f)}f=!0;if(c)for(var g=c.length-1;!a.ta&&0<=g;g--){var k=a.currentTarget=c[g];f=k.xb(d,!0,a)&&f}a.ta||(k=a.currentTarget=b,f=k.xb(d,!0,a)&&f,a.ta||(f=k.xb(d,!1,a)&&f));if(c)for(g=0;!a.ta&&g<c.length;g++)k=a.currentTarget=c[g],f=k.xb(d,!1,a)&&f;return f};
p.i=function(){P.h.i.call(this);this.ye();this.Lc=null};p.Ga=function(a,b,c,d){return this.fa.add(String(a),b,!1,c,d)};p.Ec=function(a,b,c,d){return this.fa.add(String(a),b,!0,c,d)};p.Wb=function(a,b,c,d){return this.fa.remove(String(a),b,c,d)};p.We=function(a){return this.fa.ze(a)};p.ye=function(a){return this.fa?this.fa.Rb(a):0};
p.xb=function(a,b,c){a=this.fa.o[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.Ha&&g.capture==b){var k=g.listener,l=g.Bb||g.src;g.qb&&this.We(g);d=!1!==k.call(l,c)&&d}}return d&&0!=c.Ee};p.Sa=function(a,b,c,d){return this.fa.Sa(String(a),b,c,d)};var hd="StopIteration"in r?r.StopIteration:{message:"StopIteration",stack:""},id=function(){};id.prototype.next=function(){throw hd;};id.prototype.fc=function(){return this};var jd=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},kd=function(a){a=String(a);if(jd(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var ld=function(){};ld.prototype.yd=null;ld.prototype.Rd=function(){return this.yd||(this.yd=this.Og())};var md,nd=function(){};y(nd,ld);nd.prototype.Cd=function(){var a=this.Sd();return a?new ActiveXObject(a):new XMLHttpRequest};nd.prototype.Og=function(){var a={};this.Sd()&&(a[0]=!0,a[1]=!0);return a};
nd.prototype.Sd=function(){if(!this.Xd&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++){var c=a[b];try{return new ActiveXObject(c),this.Xd=c}catch(d){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return this.Xd};md=new nd;var od=function(a,b){this.l={};this.c=[];this.lb=this.b=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};p=od.prototype;p.s=function(){return this.b};p.u=function(){this.tb();for(var a=[],b=0;b<this.c.length;b++)a.push(this.l[this.c[b]]);return a};p.M=function(){this.tb();return this.c.concat()};p.ma=function(a){return pd(this.l,a)};p.isEmpty=function(){return 0==this.b};
p.clear=function(){this.l={};this.lb=this.b=this.c.length=0};p.remove=function(a){return pd(this.l,a)?(delete this.l[a],this.b--,this.lb++,this.c.length>2*this.b&&this.tb(),!0):!1};p.tb=function(){var a,b;if(this.b!=this.c.length){for(a=b=0;b<this.c.length;){var c=this.c[b];pd(this.l,c)&&(this.c[a++]=c);b++}this.c.length=a}if(this.b!=this.c.length){var d={};for(a=b=0;b<this.c.length;)c=this.c[b],pd(d,c)||(this.c[a++]=c,d[c]=1),b++;this.c.length=a}};
p.get=function(a,b){return pd(this.l,a)?this.l[a]:b};p.set=function(a,b){pd(this.l,a)||(this.b++,this.c.push(a),this.lb++);this.l[a]=b};p.addAll=function(a){if(a instanceof od){var b=a.M();a=a.u()}else b=Mb(a),a=Lb(a);for(var c=0;c<b.length;c++)this.set(b[c],a[c])};p.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};p.clone=function(){return new od(this)};
p.fc=function(a){this.tb();var b=0,c=this.lb,d=this,f=new id;f.next=function(){if(c!=d.lb)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw hd;var f=d.c[b++];return a?f:d.l[f]};return f};var pd=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var qd=function(a){if(a.u&&typeof a.u==m)return a.u();if(u(a))return a.split("");if(ab(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Lb(a)},rd=function(a,b,c){if(a.forEach&&typeof a.forEach==m)a.forEach(b,c);else if(ab(a)||u(a))xb(a,b,c);else{if(a.M&&typeof a.M==m)var d=a.M();else if(a.u&&typeof a.u==m)d=void 0;else if(ab(a)||u(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g)}else d=Mb(a);f=qd(a);g=f.length;for(var k=0;k<g;k++)b.call(c,f[k],d&&d[k],a)}};var sd=function(a,b,c){if(bb(a))c&&(a=x(a,c));else if(a&&typeof a.handleEvent==m)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:r.setTimeout(a,b||0)};var td=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,ud=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var Q=function(a){P.call(this);this.headers=new od;this.ac=a||null;this.ba=!1;this.$b=this.a=null;this.Dc="";this.Fa=0;this.qa=this.yc=this.Eb=this.rc=!1;this.ua=0;this.Vb=null;this.Ia="";this.Zc=this.Ah=this.aa=!1};y(Q,P);var vd=/^https?$/i,wd=["POST","PUT"],xd=[],yd=function(a,b,c,d,f,g,k){var l=new Q;xd.push(l);b&&l.Ga(e,b);l.Ec(Fa,l.Zf);g&&l.Uc(g);k&&l.Vc(k);l.send(a,c,d,f);return l};p=Q.prototype;p.Zf=function(){this.na();Eb(xd,this)};p.Uc=function(a){this.ua=Math.max(0,a)};
p.Ih=function(a){this.Ia=a};p.Vc=function(a){this.aa=a};
p.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.Dc+"; newUri="+a);b=b?b.toUpperCase():"GET";this.Dc=a;this.Fa=0;this.rc=!1;this.ba=!0;this.a=this.dg();this.$b=this.ac?this.ac.Rd():md.Rd();this.a.onreadystatechange=x(this.te,this);this.Ah&&"onprogress"in this.a&&(this.a.onprogress=x(function(a){this.re(a,!0)},this),this.a.upload&&(this.a.upload.onprogress=x(this.re,this)));try{this.yc=!0,this.a.open(b,String(a),!0),this.yc=!1}catch(g){this.Kd(5,
g);return}a=c||"";var f=this.headers.clone();d&&rd(d,function(a,b){f.set(b,a)});d=Cb(f.M(),zd);c=r.FormData&&a instanceof r.FormData;!A(wd,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Ia&&(this.a.responseType=this.Ia);"withCredentials"in this.a&&this.a.withCredentials!==this.aa&&(this.a.withCredentials=this.aa);try{this.zd(),0<this.ua&&((this.Zc=Ad(this.a))?(this.a.timeout=this.ua,this.a.ontimeout=
x(this.Ue,this)):this.Vb=sd(this.Ue,this.ua,this)),this.Eb=!0,this.a.send(a),this.Eb=!1}catch(g){this.Kd(5,g)}};var Ad=function(a){return C&&H(9)&&Xa(a.timeout)&&t(a.ontimeout)},zd=function(a){return"content-type"==a.toLowerCase()};p=Q.prototype;p.dg=function(){return this.ac?this.ac.Cd():md.Cd()};p.Ue=function(){"undefined"!=typeof Wa&&this.a&&(this.Fa=8,this.dispatchEvent("timeout"),this.abort(8))};p.Kd=function(a){this.ba=!1;this.a&&(this.qa=!0,this.a.abort(),this.qa=!1);this.Fa=a;this.Hd();this.sb()};
p.Hd=function(){this.rc||(this.rc=!0,this.dispatchEvent(e),this.dispatchEvent("error"))};p.abort=function(a){this.a&&this.ba&&(this.ba=!1,this.qa=!0,this.a.abort(),this.qa=!1,this.Fa=a||7,this.dispatchEvent(e),this.dispatchEvent("abort"),this.sb())};p.i=function(){this.a&&(this.ba&&(this.ba=!1,this.qa=!0,this.a.abort(),this.qa=!1),this.sb(!0));Q.h.i.call(this)};p.te=function(){this.wa||(this.yc||this.Eb||this.qa?this.se():this.uh())};p.uh=function(){this.se()};
p.se=function(){if(this.ba&&"undefined"!=typeof Wa&&(!this.$b[1]||4!=this.zb()||2!=this.getStatus()))if(this.Eb&&4==this.zb())sd(this.te,0,this);else if(this.dispatchEvent("readystatechange"),this.Qg()){this.ba=!1;try{this.ab()?(this.dispatchEvent(e),this.dispatchEvent(Na)):(this.Fa=6,this.Hd())}finally{this.sb()}}};p.re=function(a,b){this.dispatchEvent(Bd(a,"progress"));this.dispatchEvent(Bd(a,b?"downloadprogress":"uploadprogress"))};
var Bd=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}};p=Q.prototype;p.sb=function(a){if(this.a){this.zd();var b=this.a,c=this.$b[0]?Ya:null;this.$b=this.a=null;a||this.dispatchEvent(Fa);try{b.onreadystatechange=c}catch(d){}}};p.zd=function(){this.a&&this.Zc&&(this.a.ontimeout=null);Xa(this.Vb)&&(r.clearTimeout(this.Vb),this.Vb=null)};p.Gb=function(){return!!this.a};p.Qg=function(){return 4==this.zb()};
p.ab=function(){var a=this.getStatus();a:switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var b=!0;break a;default:b=!1}return b||0===a&&!this.Rg()};p.Rg=function(){var a=String(this.Dc).match(td)[1]||null;!a&&r.self&&r.self.location&&(a=r.self.location.protocol,a=a.substr(0,a.length-1));return vd.test(a?a.toLowerCase():"")};p.zb=function(){return this.a?this.a.readyState:0};p.getStatus=function(){try{return 2<this.zb()?this.a.status:-1}catch(a){return-1}};
p.vg=function(){try{return this.a?this.a.responseText:""}catch(a){return""}};p.Td=function(a){if(this.a){var b=this.a.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));return kd(b)}};p.ug=function(){try{if(!this.a)return null;if("response"in this.a)return this.a.response;switch(this.Ia){case "":case "text":return this.a.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.a)return this.a.mozResponseArrayBuffer}return null}catch(a){return null}};var Cd=function(){};Cd.prototype.U=function(){return"NONE"};Cd.prototype.N=function(){return null};var Dd=function(a){this.label=a};y(Dd,Cd);Dd.prototype.A=function(){return this.label};var R=function(a,b){this.label=b;this.value=a.U();this.X=a};y(R,Cd);R.prototype.A=function(){return this.label};R.prototype.U=function(){return this.value};R.prototype.encode=function(){return this.X.encode()+"="};R.prototype.N=function(){return new Ed(this)};var S=function(){};y(S,Cd);S.prototype.encode=function(){return encodeURIComponent(this.U())};S.prototype.N=function(){return null};var Fd=function(a){R.call(this,a,a.A())};y(Fd,R);var Gd=function(){};y(Gd,S);Gd.prototype.A=function(){return"Anonymous"};Gd.prototype.U=function(){return"ANON"};Gd.prototype.decode=function(){return new Fd(this)};var Hd=function(a,b){this.ub=this.$c=this.Ja="";this.Qb=null;this.Qa=this.ve="";this.G=this.Sg=!1;var c;a instanceof Hd?(this.G=t(b)?b:a.G,this.Oe(a.Ja),this.Se(a.$c),this.Ie(a.ub),this.Me(a.Qb),this.setPath(a.getPath()),this.Ne(a.ha.clone()),this.Ke(a.Qa)):a&&(c=String(a).match(td))?(this.G=!!b,this.Oe(c[1]||"",!0),this.Se(c[2]||"",!0),this.Ie(c[3]||"",!0),this.Me(c[4]),this.setPath(c[5]||"",!0),this.Ne(c[6]||"",!0),this.Ke(c[7]||"",!0)):(this.G=!!b,this.ha=new Id(null,null,this.G))};p=Hd.prototype;
p.toString=function(){var a=[],b=this.Ja;b&&a.push(Jd(b,Kd,!0),":");var c=this.ub;if(c||"file"==b)a.push("//"),(b=this.$c)&&a.push(Jd(b,Kd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Qb,null!=c&&a.push(":",String(c));if(c=this.getPath())this.Hg()&&"/"!=c.charAt(0)&&a.push("/"),a.push(Jd(c,"/"==c.charAt(0)?Ld:Md,!0));(c=this.og())&&a.push("?",c);(c=this.Qa)&&a.push("#",Jd(c,Nd));return a.join("")};p.clone=function(){return new Hd(this)};
p.Oe=function(a,b){this.ea();if(this.Ja=b?Od(a,!0):a)this.Ja=this.Ja.replace(/:$/,"");return this};p.Se=function(a,b){this.ea();this.$c=b?Od(a):a;return this};p.Ie=function(a,b){this.ea();this.ub=b?Od(a,!0):a;return this};p.Hg=function(){return!!this.ub};p.Me=function(a){this.ea();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.Qb=a}else this.Qb=null;return this};p.getPath=function(){return this.ve};p.setPath=function(a,b){this.ea();this.ve=b?Od(a,!0):a;return this};
p.Ne=function(a,b){this.ea();a instanceof Id?(this.ha=a,this.ha.Tc(this.G)):(b||(a=Jd(a,Pd)),this.ha=new Id(a,null,this.G));return this};p.og=function(){return this.ha.toString()};p.Ub=function(a,b){this.ea();this.ha.set(a,b);return this};p.Ke=function(a,b){this.ea();this.Qa=b?Od(a):a;return this};p.ea=function(){if(this.Sg)throw Error("Tried to modify a read-only Uri");};p.Tc=function(a){this.G=a;this.ha&&this.ha.Tc(a);return this};
var Od=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Jd=function(a,b,c){return u(a)?(a=encodeURI(a).replace(b,Qd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Qd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Kd=/[#\/\?@]/g,Md=/[\#\?:]/g,Ld=/[\#\?]/g,Pd=/[\#\?@]/g,Nd=/#/g,Id=function(a,b,c){this.b=this.g=null;this.da=a||null;this.G=!!c};p=Id.prototype;
p.S=function(){if(!this.g&&(this.g=new od,this.b=0,this.da)){var a=this;ud(this.da,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)})}};p.s=function(){this.S();return this.b};p.add=function(a,b){this.S();this.Ea();a=this.Aa(a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.b+=1;return this};p.remove=function(a){this.S();a=this.Aa(a);return this.g.ma(a)?(this.Ea(),this.b-=this.g.get(a).length,this.g.remove(a)):!1};p.clear=function(){this.Ea();this.g=null;this.b=0};
p.isEmpty=function(){this.S();return 0==this.b};p.ma=function(a){this.S();a=this.Aa(a);return this.g.ma(a)};p.forEach=function(a,b){this.S();this.g.forEach(function(c,d){xb(c,function(c){a.call(b,c,d,this)},this)},this)};p.M=function(){this.S();for(var a=this.g.u(),b=this.g.M(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};p.u=function(a){this.S();var b=[];if(u(a))this.ma(a)&&(b=Fb(b,this.g.get(this.Aa(a))));else{a=this.g.u();for(var c=0;c<a.length;c++)b=Fb(b,a[c])}return b};
p.set=function(a,b){this.S();this.Ea();a=this.Aa(a);this.ma(a)&&(this.b-=this.g.get(a).length);this.g.set(a,[b]);this.b+=1;return this};p.get=function(a,b){a=a?this.u(a):[];return 0<a.length?String(a[0]):b};p.setValues=function(a,b){this.remove(a);0<b.length&&(this.Ea(),this.g.set(this.Aa(a),Gb(b)),this.b+=b.length)};
p.toString=function(){if(this.da)return this.da;if(!this.g)return"";for(var a=[],b=this.g.M(),c=0;c<b.length;c++){var d=b[c],f=encodeURIComponent(String(d));d=this.u(d);for(var g=0;g<d.length;g++){var k=f;""!==d[g]&&(k+="="+encodeURIComponent(String(d[g])));a.push(k)}}return this.da=a.join("&")};p.Ea=function(){this.da=null};p.clone=function(){var a=new Id;a.da=this.da;this.g&&(a.g=this.g.clone(),a.b=this.b);return a};p.Aa=function(a){a=String(a);this.G&&(a=a.toLowerCase());return a};
p.Tc=function(a){a&&!this.G&&(this.S(),this.Ea(),this.g.forEach(function(a,c){var b=c.toLowerCase();c!=b&&(this.remove(c),this.setValues(b,a))},this));this.G=a};var Rd="";var Sd=function(){"loading"!=document.readyState?this.$d():O(window,"load",this.$d)};Sd.prototype.$d=function(){var a=Array.prototype.slice.call(document.getElementsByTagName("link"),0);Ua();var b=a[Symbol.iterator];a=b?b.call(a):Ta(a);for(b=a.next();!b.done;b=a.next())b=b.value,b.getAttribute("data-async-css")==Oa&&b.getAttribute("media")==n&&b.setAttribute("media","all")};var Td=function(a){if(a.classList)return a.classList;a=a.className;return u(a)&&a.match(/\S+/g)||[]},Ud=function(a,b){return a.classList?a.classList.contains(b):A(Td(a),b)},Vd=function(a,b){a.classList?a.classList.add(b):Ud(a,b)||(a.className+=0<a.className.length?" "+b:b)},Wd=function(a,b){a.classList?a.classList.remove(b):Ud(a,b)&&(a.className=yb(Td(a),function(a){return a!=b}).join(" "))};var Xd=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=F&&!b&&!c;if((!t(b)||d)&&a.getBoundingClientRect){a:{try{var f=a.getBoundingClientRect()}catch(g){f={left:0,top:0,right:0,bottom:0};break a}C&&a.ownerDocument.body&&(a=a.ownerDocument,f.left-=a.documentElement.clientLeft+a.body.clientLeft,f.top-=a.documentElement.clientTop+a.body.clientTop)}return new xc(f.right-f.left,f.bottom-f.top)}return new xc(b,c)},Zd=function(a,b){b=zc(b);var c=b.oa;if(C&&c.createStyleSheet){var d=c.createStyleSheet();
Yd(d,a)}else c=b.Md("HEAD")[0],c||(d=b.Md("BODY")[0],c=b.mc("HEAD"),d.parentNode.insertBefore(c,d)),d=b.mc("STYLE"),Yd(d,a),b.appendChild(c,d);return d},Yd=function(a,b){b=vc(b);C&&t(a.cssText)?a.cssText=b:a.innerHTML=b};/*

 CC0 1.0 Universal License
 Public Domain Dedication

 The person(s) who associated a work with this deed has dedicated the work to
 the public domain by waiving all of his or her rights to the work worldwide
 under copyright law, including all related and neighboring rights, to the
 extent allowed by law.

 You can copy, modify, distribute and perform the work, even for commercial
 purposes, all without asking permission.

 In no way are the patent or trademark rights of any person affected by CC0,
 nor are the rights that other persons may have in the work or in how the work
 is used, such as publicity or privacy rights.

 Unless expressly stated otherwise, the person(s) who associated a work with
 this deed makes no warranties about the work, and disclaims liability for all
 uses of the work, to the fullest extent permitted by applicable law.

 When using or citing the work, you should not imply endorsement by the author
 or the affirmer.

 This is a human-readable summary of the Legal Code (read the full text).
 svg4everybody v2.1.8 | github.com/jonathantneal/svg4everybody */
function $d(a,b,c){if(c){var d=document.createDocumentFragment(),f=!b.hasAttribute("viewBox")&&c.getAttribute("viewBox");f&&b.setAttribute("viewBox",f);for(b=c.cloneNode(!0);b.childNodes.length;)d.appendChild(b.firstChild);a.appendChild(d)}}
function ae(a){a.onreadystatechange=function(){if(4===a.readyState){var b=a.Nf;b||(b=a.Nf=document.implementation.createHTMLDocument(""),b.body.innerHTML=a.responseText,a.nd={});a.od.splice(0).map(function(c){var d=a.nd[c.id];d||(d=a.nd[c.id]=b.getElementById(c.id));$d(c.parent,c.Mh,d)})}};a.onreadystatechange()}function be(){return"undefined"!=typeof LEGACY_SUPPORT&&LEGACY_SUPPORT}
var ce=function(a){function b(){for(var a=0;a<zb.length;){var g=zb[a],k=g.parentNode,l;for(l=k;"svg"!==l.nodeName.toLowerCase()&&(l=l.parentNode,l););if(l){var q=g.getAttribute("xlink:href")||g.getAttribute("href");!q&&c.attributeName&&(q=g.getAttribute(c.attributeName));if(be()&&f){var M=document.createElement("img");M.style.cssText="display:inline-block;height:100%;width:100%";M.setAttribute("width",l.getAttribute("width")||l.clientWidth);M.setAttribute("height",l.getAttribute("height")||l.clientHeight);
M.src=d(q,l,g);k.replaceChild(M,g)}else ie&&(!c.Ph||c.Ph(q,l,g)?(k.removeChild(g),q=q.split("#"),g=q.shift(),q=q.join("#"),g.length?(M=je[g],M||(M=je[g]=new XMLHttpRequest,M.open("GET",g),M.send(),M.od=[]),M.od.push({parent:k,Mh:l,id:q}),ae(M)):$d(k,l,document.getElementById(q))):(++a,++ke))}else++a}if(!zb.length||0<zb.length-ke)window.requestAnimationFrame?window.requestAnimationFrame(b):setTimeout(b,67)}var c=Object(a);if(be()){var d=c.Vh||function(a){return a.replace(/\?[^#]+/,"").replace("#",
".").replace(/^\./,"")+".png"+(/\?[^#]+/.exec(a)||[""])[0]};var f="nosvg"in c?c.Xh:/\bMSIE [1-8]\b/.test(navigator.userAgent)}a=/\bMSIE [1-8]\.0\b/;var g=/\bTrident\/[567]\b|\bMSIE (?:9|10)\.0\b/,k=/\bAppleWebKit\/(\d+)\b/,l=/\bEdge\/12\.(\d+)\b/,q=/\bEdge\/.(\d+)\b/,ba=window.top!==window.self;var ie="polyfill"in c?c.Zh:be()?a.test(navigator.userAgent)||g.test(navigator.userAgent)||10547>(navigator.userAgent.match(l)||[])[1]||537>(navigator.userAgent.match(k)||[])[1]||q.test(navigator.userAgent)&&
ba:g.test(navigator.userAgent)||10547>(navigator.userAgent.match(l)||[])[1]||537>(navigator.userAgent.match(k)||[])[1]||q.test(navigator.userAgent)&&ba;var je={},zb=document.getElementsByTagName("use"),ke=0;ie&&b()};var de=function(a){return/^[A-Za-z0-9]+$/.test(a)||/^#[0-9A-Fa-f]{3}$/.test(a)||/^#[0-9A-Fa-f]{6}$/.test(a)||/^rgb *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)||/^rgba *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)},ee=function(a){a=a.split(",");for(var b=0;b<a.length;b++){var c=a[b];c=lb(c);if(!(/^[- A-Za-z0-9]*$/.test(c)||/^"[- A-Za-z0-9]*"$/.test(c)||/^'[- A-Za-z0-9]*'$/.test(c)))return!1}return!0},fe=function(){if(window.parent&&window.parent.postMessage){var a=
document.getElementById("previewHolder"),b=0;if(a){b:{b=9==a.nodeType?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue("display")||"";break b}b=""}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display)!=n)a=Xd(a);else{b=a.style;var c=b.display,d=b.visibility,f=b.position;b.visibility=pa;b.position="absolute";b.display="inline";a=Xd(a);b.display=c;b.position=f;b.visibility=
d}b=a.height}b=(b=Math.max(b,document.body.scrollHeight))||230;a="amp=1"==(new Hd(document.location.href)).Qa?{sentinel:"amp",type:"embed-size",height:b}:"set-comment-editor-height "+b+"px";window.parent.postMessage(a,"*")}},ge=function(){var a=document.getElementById(ia),b=document.getElementById(Ea),c=document.getElementById("postCommentPreview"),d=function(){b&&(b.disabled=""==a.value);c&&(c.disabled=""==a.value)};a&&"oninput"in a&&(d(null),O(a,ta,d))},he=function(a){var b=[];C&&b.push(uc(".previewMode .postCommentButtonHolder",
{"padding-top":"22px"}));var c=(new Hd(a)).Qa;if(0!=c.length){a=null;try{c=decodeURIComponent(c),a=kd(c)}catch(k){}if(a&&a.color){c=kb(jb(a.color));var d=kb(jb(a.unvisitedLinkColor));a=kb(jb(a.fontFamily));de(c)&&de(d)&&ee(a)&&(b.push(uc("body",{color:c,"font-family":a})),b.push(uc("a:link, a:visited, a:active, a:hover",{color:d})))}}Zd(wc(b));setTimeout(fe,100);var f=J(da);if((b=J(ia))&&f){var g=!1;O(b,"focus",function(){g||(g=!0,Wd(f,"compact"),fe())})}ce();new Sd};var T=function(a){a=J(a);var b=a.nodeName.toLowerCase();a.style.display="span"==b||"img"==b||"a"==b||b==ta||"select"==b?"inline":"block"},U=function(a){J(a).style.display=n};var V=function(a,b,c){var d;c&&U(xa);switch(a){case 0:a=d="captcha-error";break;case 1:a=d="id-error";break;case 2:case 3:case 4:a="main-error";d="main-error-holder";break;case 5:a=d="nameUrlDialogErrorHolder";break;case 6:a=d="openIdDialogErrorHolder";break;case 7:a=d="genericOpenIdDialogErrorHolder";break;default:throw Error("internal error in show message");}c?(J(a).innerHTML=b,T(d),J(ia).className="commentBody-err"):(Gc(J(a)),U(d));fe()},le=function(a){V(3,null,!1);J("main-status").innerHTML=
a;T(xa);fe()};var me=function(){};me.prototype.Lh=function(){U(sa);J(ia).disabled=!0;J(Ea).disabled=!0};me.prototype.Ig=function(){T(sa);J(ia).disabled=!1;J(Ea).disabled=!1};var Ed=function(a){this.m=a};y(Ed,me);p=Ed.prototype;p.ra=function(){return!1};p.ia=function(){if(!this.ra())throw Error("Trying to show a non-editable identity");this.Lh();T(ra)};p.Ib=function(){return!0};p.Wc=function(){if(!this.ra())throw Error("Trying to show edit button for a non-editable identity");T("editButton")};p.eb=function(){};p.hb=function(){};p.Z=function(){U(ra);U("editButton");U("settingsButton");U("commentDash");U(Ma);this.Ig()};var ne=function(a){a=a.className;return u(a)&&a.match(/\S+/g)||[]},oe=function(a,b){for(var c=ne(a),d=Hb(arguments,1),f=c.length+d.length,g=0;g<d.length;g++)A(c,d[g])||c.push(d[g]);a.className=c.join(" ");return c.length==f},qe=function(a,b){var c=ne(a),d=Hb(arguments,1),f=pe(c,d);a.className=f.join(" ");return f.length==c.length-d.length},pe=function(a,b){return yb(a,function(a){return!A(b,a)})};var te=function(a){for(var b=[],c=re,d,f=a.elements,g,k=0;g=f[k];k++)if(g.form==a&&!g.disabled&&"FIELDSET"!=g.tagName)switch(d=g.name,g.type.toLowerCase()){case "file":case "submit":case "reset":case "button":break;case Ia:g=se(g);if(null!=g)for(var l,q=0;l=g[q];q++)c(b,d,l);break;default:l=se(g),null!=l&&c(b,d,l)}f=a.getElementsByTagName("INPUT");for(k=0;g=f[k];k++)g.form==a&&"image"==g.type.toLowerCase()&&(d=g.name,c(b,d,g.value),c(b,d+".x","0"),c(b,d+".y","0"));return b.join("&")},re=function(a,
b,c){a.push(encodeURIComponent(b)+"="+encodeURIComponent(c))},se=function(a){var b=a.type;switch(u(b)&&b.toLowerCase()){case "checkbox":case "radio":return a.checked?a.value:null;case "select-one":return b=a.selectedIndex,0<=b?a.options[b].value:null;case Ia:b=[];for(var c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:null;default:return null!=a.value?a.value:null}};var ue=!1,ve=!1,we=!1,xe=function(a,b){ve=a;we=b;window.parent==window.top&&(a||b)?(a=J(Ma),b?oe(a,"checked"):qe(a,"checked"),T(Ma),J("ajaxAction").value=b?"UnsubscribeByEmail":"SubscribeByEmail"):U(Ma)};var ze=function(a,b){R.call(this,new ye,a);this.ng=b};y(ze,R);ze.prototype.encode=function(){return this.X.encode()+"="+this.label+"="+this.ng};ze.prototype.A=function(){return this.label+" (Google)"};ze.prototype.N=function(){return new Ae(this)};var ye=function(){};y(ye,S);ye.prototype.A=function(){return""};ye.prototype.U=function(){return"CURRENT"};ye.prototype.decode=function(a){return new ze(a[1],a[2])};ye.prototype.N=function(){throw Error("internal error");};var Ae=function(a){this.m=a};
y(Ae,Ed);Ae.prototype.Wc=function(){(ve||we)&&T(Ma)};var Be=function(a){R.call(this,a,a.A())};y(Be,R);var Ce=function(){};y(Ce,S);Ce.prototype.A=function(){return"Google Account"};Ce.prototype.U=function(){return"GOOGLE"};Ce.prototype.decode=function(){return this.Qd()};Ce.prototype.Qd=function(){return new Be(this)};var De=function(a,b,c){R.call(this,a,null);this.name=b;this.url=c};y(De,R);De.prototype.A=function(){return this.name+" ("+this.url+")"};De.prototype.encode=function(){return this.X.encode()+"="+encodeURIComponent(this.name)+"="+encodeURIComponent(this.url)};De.prototype.N=function(){return new Ee(this)};var Fe=function(){};y(Fe,S);Fe.prototype.A=function(){return"Name/URL"};Fe.prototype.U=function(){return"NAMEURL"};Fe.prototype.N=function(){return new Ee(new De(this,"",""))};
Fe.prototype.decode=function(a){return new De(this,a[1],a[2])};var Ee=function(a){this.m=a};y(Ee,Ed);p=Ee.prototype;p.ra=function(){return!0};p.ia=function(){Ee.h.ia.call(this);T(ya)};p.Z=function(){Ee.h.Z.call(this);U(ya);V(5,null,!1);this.Le("");this.Re("")};p.eb=function(){this.Le(this.m.name);this.Re(this.m.url)};p.hb=function(){Ee.h.hb.call(this);this.m.name=this.Pd();this.m.url=this.yg();this.Wc()};p.Ib=function(){return""==this.Pd()?(V(5,"Name should not be empty",!0),!1):!0};p.Pd=function(){return J("anonNameField").value};
p.Le=function(a){J("anonNameField").value=a};p.yg=function(){return J("anonUrlField").value};p.Re=function(a){J("anonUrlField").value=a};var Ge=function(){this.pa=[];this.cb=[];this.Na=[];this.Xa=[];this.j=this.D=null;this.H=[]};p=Ge.prototype;p.Fb=function(a,b,c,d){for(var f=0;f<this.H.length;f++)if(a==this.H[f])return d(a);d=a.encode();for(f=0;f<this.H.length;f++)if(this.H[f].encode()==d)return c(this.H[f]);return b(a)};p.Ng=function(a){return this.Fb(a,x(function(a){return this.H[this.H.length]=a},this),Hc,Hc)};p.Hb=function(a){function b(){return!1}return this.Fb(a,function(){return!0},b,b)};
p.$a=function(a){function b(){throw Error("item should have been unique");}this.Fb(a,Ya,b,b);return this.Ng(a)};p.hc=function(a){return this.Fb(a,x(function(a){this.H[this.H.length]=a;return this.pa[this.pa.length]=a},this),Hc,Hc)};p.le=function(){for(var a=document.getElementById("identityControlsHolder"),b=Td(a),c=0;c<b.length;c++)b[c].slice(0,14)==qa&&Wd(a,b[c]);(b=this.Xa[J(sa).selectedIndex])&&Vd(a,qa+b.value)};p.rd=function(a){this.D=this.hc(a);this.gb();this.Ma();this.pb(!1);return this.D};
p.la=function(a){this.$a(a);this.cb[this.cb.length]=a};p.Rf=function(){var a=this.$a(new Ce);this.la(a.Qd())};p.Qf=function(){var a=new Fe;this.$a(a);this.Na[this.Na.length]=a};p.Pf=function(){var a=this.$a(new Gd);a=this.$a(new Fd(a));this.Na[this.Na.length]=a};p.Ma=function(){var a=this.Xa[J(sa).selectedIndex];a.constructor==Dd?this.gb():(V(1,null,!1),this.j=a.N(),null!=this.j&&this.j.eb(),this.le())};
p.pb=function(a){if(null!=this.j){var b=this.j.m;if(a&&this.j.ra()&&this.Hb(b)||!this.j.Ib())this.j.ia();else return this.j.hb(),this.j.Z(),this.j.ra()&&this.j.Wc(),this.j=null,b}return null};p.Dh=function(){this.eg(J("encodedIds").value);this.D=this.Ed(J(la).value);null==this.D&&0<this.pa.length&&(this.D=this.pa[0]);null==this.D&&1==this.cb.length&&(this.D=this.cb[0]);this.gb();null!=this.D&&(this.Ma(),this.pb(!1))};
p.sd=function(a,b){this.Xa[this.Xa.length]=b;var c=document.createElement("option");c.text=b.A();c.value=b.U();try{a.add(c,null)}catch(d){a.add(c)}this.D==b&&(c.selected=!0);return c};p.ic=function(a,b){for(var c=0;c<b.length;c++)this.sd(a,b[c])};p.gb=function(){for(var a=J(sa);0!=a.options.length;)a.remove(0);this.Xa=[];this.sd(a,new Dd("Select profile...")).disabled="disabled";this.ic(a,this.pa);this.ic(a,this.cb);this.ic(a,this.Na)};
p.kg=function(){for(var a=[],b=0;b<this.pa.length;b++)a[a.length]=this.pa[b].encode();return a.join("&")};p.eg=function(a){if(""!=a){a=a.split("&");for(var b=0;b<a.length;b++)this.Ed(a[b])}};p.Ed=function(a){if(""==a)return null;a=a.split("=");for(var b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);b=this.mg(a[0]);return null!=b?(a=b.decode(a),this.hc(a)):null};p.mg=function(a){for(var b=0;b<this.H.length;b++)if(this.H[b].encode()==a)return this.H[b];return null};
p.$e=function(){var a=J(ia).value;if(""==a)return V(2,"Comment should not be empty",!0),!1;if(1E6<a.length)return V(2,"Content length exceeds 1MB. Please abridge.",!0),!1;V(2,null,!1);return!0};p.Jc=function(){null!=this.j&&this.j.Z();this.Ma();var a=this.pb(!0);null!=a&&(this.D=a)};p.kh=function(){var a=this.pb(!1);null!=a&&this.rd(a)};p.jh=function(){null!=this.j&&(this.j.Z(),this.j=null);this.gb();this.Jc()};
p.ue=function(){if(null==this.D||"NONE"==this.D.U())return V(1,"Please choose a profile",!0),!1;if(null!=this.j)return!1;J("encodedIds").value=this.kg();J(la).value=this.D.encode();return!0};p.mh=function(){this.D&&(this.Ma(),this.j.ia())};p.sh=function(){this.$e()&&this.ue()&&this.Id(!1)};p.th=function(){this.$e()&&this.ue()&&this.Id(!0)};p.Id=function(a){J(Ja).value=a?Oa:"false";this.Ma();a=J("commentForm");a.onsubmit();a.submit()};var He=function(a,b,c,d){this.fg=a;this.Ye=b;this.name=c;this.Oh=d};y(He,S);p=He.prototype;p.A=function(){return this.name};p.encode=function(){return encodeURIComponent(this.fg)};p.$f=function(a){return this.Ye.replace(/{username}/,encodeURIComponent(a))};p.xg=function(){return this.Ye.split("{username}")};p.N=function(){return new Ie(new Je(this,"",""))};p.decode=function(a){return new Je(this,a[1],a[2])};var Je=function(a,b,c){R.call(this,a,b);this.username=c;this.uri=b;this.value="OPENID"};
y(Je,R);Je.prototype.A=function(){return this.username+" ("+this.X.A()+")"};Je.prototype.encode=function(){return this.X.encode()+"="+encodeURIComponent(this.uri)+"="+encodeURIComponent(this.username)};Je.prototype.N=function(){return new Ie(this)};var Ie=function(a){this.m=a};y(Ie,Ed);p=Ie.prototype;p.ra=function(){return!0};
p.ia=function(){Ie.h.ia.call(this);T(Ba);J("openIdUsernameLabel").innerHTML=this.m.X.Oh;for(var a=J(Da),b=x(function(){this.xe()},this),c=["change",ua,"keydown","keyup","blur","focus"],d=0;d<c.length;d++)O(a,c[d],b)};p.Z=function(){Ie.h.Z.call(this);dd(J(Da));U(Ba);V(6,null,!1);J(Ca).value=""};p.eb=function(){this.Kh(this.m.username);J(Ca).value=this.m.X.$f(this.m.username)};p.hb=function(){this.m.username=this.sc();this.eb()};
p.Ib=function(){return""==this.sc()?(V(6,"The username should not be empty",!0),!1):!0};p.xe=function(){var a=this.m.X.xg(),b=this.sc();b=""==b?"username":encodeURIComponent(b);J("openIdUriDisplayPrefix").innerHTML=a[0];J("openIdUriDisplayUsername").innerHTML=b;J("openIdUriDisplaySuffix").innerHTML=a[1]};p.sc=function(){return J(Da).value};p.Kh=function(a){J(Da).value=a;this.xe()};var Ke=function(){};y(Ke,S);Ke.prototype.A=function(){return"OpenID"};Ke.prototype.U=function(){return"OPENID"};
Ke.prototype.decode=function(a){return new Le(this,a[1])};Ke.prototype.N=function(){return new Me(new Le(this,""))};var Le=function(a,b){R.call(this,a,b);this.uri=b;this.value="OPENID"};y(Le,R);Le.prototype.A=function(){return this.uri};Le.prototype.encode=function(){return this.X.encode()+"="+encodeURIComponent(this.uri)};Le.prototype.N=function(){return new Me(this)};var Me=function(a){this.m=a};y(Me,Ed);p=Me.prototype;p.ra=function(){return!0};p.ia=function(){Me.h.ia.call(this);T(ma)};
p.Z=function(){Me.h.Z.call(this);U(ma);V(7,null,!1);this.Qe("")};p.eb=function(){this.Qe(this.m.uri)};p.hb=function(){this.m.uri=this.Ud()};p.Ib=function(){return""==this.Ud()?(V(7,"The URL should not be empty",!0),!1):!0};p.Ud=function(){return J(Ca).value};p.Qe=function(a){J(Ca).value=a};var Ne=function(){qe(J(da),"previewMode");return!0};var Oe;Rb("A AREA BUTTON HEAD INPUT LINK MENU META OPTGROUP OPTION PROGRESS STYLE SELECT SOURCE TEXTAREA TITLE TRACK".split(" "));var Pe=function(a,b,c){K.call(this);this.Fc=a;this.Pg=b||0;this.Ca=c;this.Wf=x(this.hg,this)};y(Pe,K);p=Pe.prototype;p.Ua=0;p.i=function(){Pe.h.i.call(this);this.stop();delete this.Fc;delete this.Ca};p.start=function(a){this.stop();this.Ua=sd(this.Wf,t(a)?a:this.Pg)};p.stop=function(){this.Gb()&&r.clearTimeout(this.Ua);this.Ua=0};p.Gb=function(){return 0!=this.Ua};p.hg=function(){this.Ua=0;this.Fc&&this.Fc.call(this.Ca)};var Qe=function(a){K.call(this);this.Ca=a;this.c={}};y(Qe,K);var Re=[];p=Qe.prototype;p.Ga=function(a,b,c,d){return this.Ug(a,b,c,d)};p.Ug=function(a,b,c,d,f){w(b)||(b&&(Re[0]=b.toString()),b=Re);for(var g=0;g<b.length;g++){var k=O(a,b[g],c||this.handleEvent,d||!1,f||this.Ca||this);if(!k)break;this.c[k.key]=k}return this};p.Ec=function(a,b,c,d){return this.ke(a,b,c,d)};
p.ke=function(a,b,c,d,f){if(w(b))for(var g=0;g<b.length;g++)this.ke(a,b[g],c,d,f);else{a=Vc(a,b,c||this.handleEvent,d,f||this.Ca||this);if(!a)return this;this.c[a.key]=a}return this};p.Wb=function(a,b,c,d,f){if(w(b))for(var g=0;g<b.length;g++)this.Wb(a,b[g],c,d,f);else c=c||this.handleEvent,d=cb(d)?!!d.capture:!!d,f=f||this.Ca||this,c=Wc(c),d=!!d,b=Nc(a)?a.Sa(b,c,d,f):a?(a=Yc(a))?a.Sa(b,c,d,f):null:null,b&&(cd(b),delete this.c[b.key]);return this};
p.Rb=function(){Kb(this.c,function(a,b){this.c.hasOwnProperty(b)&&cd(a)},this);this.c={}};p.i=function(){Qe.h.i.call(this);this.Rb()};p.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Ue=function(a,b,c,d,f,g){if(!(C||D||F&&H("525")))return!0;if(G&&f)return Se(a);if(f&&!d)return!1;Xa(b)&&(b=Te(b));f=17==b||18==b||G&&91==b;if((!c||G)&&f||G&&16==b&&(d||g))return!1;if((F||D)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(C&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!(F||D)}return Se(a)},Se=function(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||(F||D)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;
default:return!1}},Te=function(a){if(E)a=Ve(a);else if(G&&F)switch(a){case 93:a=91}return a},Ve=function(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};var We=function(a,b){P.call(this);a&&this.ud(a,b)};y(We,P);p=We.prototype;p.xa=null;p.Jb=null;p.Ac=null;p.Kb=null;p.I=-1;p.sa=-1;p.jc=!1;
var Xe={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Ye={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Ze=C||D||F&&H("525"),$e=G&&E;p=We.prototype;
p.Eg=function(a){(F||D)&&(17==this.I&&!a.ctrlKey||18==this.I&&!a.altKey||G&&91==this.I&&!a.metaKey)&&this.Ce();-1==this.I&&(a.ctrlKey&&17!=a.keyCode?this.I=17:a.altKey&&18!=a.keyCode?this.I=18:a.metaKey&&91!=a.keyCode&&(this.I=91));Ze&&!Ue(a.keyCode,this.I,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?this.handleEvent(a):(this.sa=Te(a.keyCode),$e&&(this.jc=a.altKey))};p.Ce=function(){this.sa=this.I=-1};p.Fg=function(a){this.Ce();this.jc=a.altKey};
p.handleEvent=function(a){var b=a.ya,c=b.altKey;if(C&&a.type==ua){var d=this.sa;var f=13!=d&&27!=d?b.keyCode:0}else(F||D)&&a.type==ua?(d=this.sa,f=0<=b.charCode&&63232>b.charCode&&Se(d)?b.charCode:0):Ub&&!F?(d=this.sa,f=Se(d)?b.keyCode:0):(d=b.keyCode||this.sa,f=b.charCode||0,$e&&(c=this.jc),G&&63==f&&224==d&&(d=191));var g=d=Te(d);d?63232<=d&&d in Xe?g=Xe[d]:25==d&&a.shiftKey&&(g=9):b.keyIdentifier&&b.keyIdentifier in Ye&&(g=Ye[b.keyIdentifier]);a=g==this.I;this.I=g;b=new af(g,f,a,b);b.altKey=c;
this.dispatchEvent(b)};p.Ra=function(){return this.xa};p.ud=function(a,b){this.Kb&&this.detach();this.xa=a;this.Jb=O(this.xa,ua,this,b);this.Ac=O(this.xa,"keydown",this.Eg,b,this);this.Kb=O(this.xa,"keyup",this.Fg,b,this)};p.detach=function(){this.Jb&&(cd(this.Jb),cd(this.Ac),cd(this.Kb),this.Kb=this.Ac=this.Jb=null);this.xa=null;this.sa=this.I=-1};p.i=function(){We.h.i.call(this);this.detach()};var af=function(a,b,c,d){N.call(this,d);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c};
y(af,N);var bf={},cf=null,df=function(a){a=a[db]||(a[db]=++eb);delete bf[a];Ob(bf)&&cf&&cf.stop()},ff=function(){cf||(cf=new Pe(function(){ef(hb())},20));var a=cf;a.Gb()||a.start()},ef=function(a){Kb(bf,function(b){b.hh(a)});Ob(bf)||ff()};var gf=function(){P.call(this);this.Ka=0;this.endTime=this.startTime=null};y(gf,P);p=gf.prototype;p.Jh=function(){this.Ka=1};p.Pe=function(){this.Ka=0};p.ce=function(){return 1==this.Ka};p.be=function(){return-1==this.Ka};p.de=function(){return 0==this.Ka};p.ih=function(){this.V("begin")};p.qe=function(){this.V("end")};p.oh=function(){this.V("finish")};p.rh=function(){this.V("play")};p.vh=function(){this.V("resume")};p.wh=function(){this.V("stop")};p.V=function(a){this.dispatchEvent(a)};var hf=function(a,b,c,d){gf.call(this);if(!w(a)||!w(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.jb=a;this.lg=b;this.duration=c;this.qd=d;this.coords=[];this.progress=0};y(hf,gf);p=hf.prototype;
p.play=function(a){if(a||this.de())this.progress=0,this.coords=this.jb;else if(this.ce())return!1;df(this);this.startTime=a=hb();this.be()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.progress||this.ih();this.rh();this.be()&&this.vh();this.Jh();var b=this[db]||(this[db]=++eb);b in bf||(bf[b]=this);ff();this.Dd(a);return!0};p.stop=function(a){df(this);this.Pe();a&&(this.progress=1);this.Xe(this.progress);this.wh();this.qe()};
p.i=function(){this.de()||this.stop(!1);this.lh();hf.h.i.call(this)};p.hh=function(a){this.Dd(a)};p.Dd=function(a){a<this.startTime&&(this.endTime=a+this.endTime-this.startTime,this.startTime=a);this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<this.progress&&(this.progress=1);this.Xe(this.progress);1==this.progress?(this.Pe(),df(this),this.oh(),this.qe()):this.ce()&&this.dh()};
p.Xe=function(a){bb(this.qd)&&(a=this.qd(a));this.coords=Array(this.jb.length);for(var b=0;b<this.jb.length;b++)this.coords[b]=(this.lg[b]-this.jb[b])*a+this.jb[b]};p.dh=function(){this.V("animate")};p.lh=function(){this.V("destroy")};p.V=function(a){this.dispatchEvent(new jf(a,this))};var jf=function(a,b){L.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.state=b.Ka};y(jf,L);var kf=function(a,b,c,d,f){function g(a){a&&(a.tabIndex=0,a.setAttribute("role","tab"),Vd(a,"goog-zippy-header"),k.jg(a),k.ig(a))}P.call(this);this.qc=f||zc();this.ca=this.qc.Ra(a)||null;this.Pa=this.qc.Ra(d||null);this.W=(this.Mb=bb(b)?b:null)||!b?null:this.qc.Ra(b);this.T=1==c;t(c)||this.Mb||(this.Pa?this.T=this.Pa.style.display!=n:this.ca&&(this.T=Ud(this.ca,oa)));this.je=new Qe(this);this.Bc=new We;this.oe=new Qe(this);var k=this;g(this.ca);g(this.Pa);this.Tb(this.T)};y(kf,P);p=kf.prototype;
p.i=function(){kf.h.i.call(this);Ic(this.je);Ic(this.Bc);Ic(this.oe)};p.collapse=function(){this.Tb(!1)};p.toggle=function(){this.Tb(!this.T)};p.Tb=function(a){this.W?this.W.style.display=a?"":n:a&&this.Mb&&(this.W=this.Mb());this.W&&Vd(this.W,"goog-zippy-content");this.Pa?(this.ca.style.display=a?n:"",this.Pa.style.display=a?"":n):this.Yc(a);this.Je(a);this.dispatchEvent(new lf("toggle",this,this.T))};p.Je=function(a){this.T=a};
p.Yc=function(a){if(this.ca){var b=this.ca;a?Vd(b,oa):Wd(b,oa);b=this.ca;a?Wd(b,na):Vd(b,na);b=this.ca;w(a)&&(a=a.join(" "));""===a||void 0==a?(Oe||(Oe={atomic:!1,autocomplete:n,dropeffect:n,haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:n,busy:!1,disabled:!1,hidden:!1,invalid:"false"}),a=Oe,"expanded"in a?b.setAttribute(ea,a.expanded):b.removeAttribute(ea)):b.setAttribute(ea,a)}};
p.ig=function(a){a&&(this.Bc.ud(a),this.je.Ga(this.Bc,"key",this.qh))};p.jg=function(a){a&&this.oe.Ga(a,"click",this.ph)};p.qh=function(a){if(13==a.keyCode||32==a.keyCode)this.toggle(),this.Gd(a),a.preventDefault(),a.stopPropagation()};p.ph=function(a){this.toggle();this.Gd(a)};p.Gd=function(a){this.dispatchEvent(new lf("action",this,this.T,a))};var lf=function(a,b){L.call(this,a,b)};y(lf,L);var mf=function(a,b,c,d){d=d||zc();var f=d.mc("DIV",{style:"overflow:hidden"});b=d.Ra(b);b.parentNode.replaceChild(f,b);f.appendChild(b);this.vb=f;this.K=null;kf.call(this,a,b,c,void 0,d);a=this.T;this.vb.style.display=a?"":n;this.Yc(a)};y(mf,kf);p=mf.prototype;p.Uf=500;p.Tf=function(a){return 1-Math.pow(1-a,3)};
p.Tb=function(a){if(this.T!=a||this.K){this.vb.style.display==n&&(this.vb.style.display="");var b=this.W.offsetHeight;if(this.K){a=this.T;dd(this.K);this.K.stop(!1);var c=b-Math.abs(parseInt(this.W.style.marginTop,10))}else c=a?0:b;this.Yc(a);this.K=new hf([0,c],[0,a?b:0],this.Uf,this.Tf);O(this.K,["begin","animate","end"],this.eh,!1,this);O(this.K,"begin",x(this.fh,this,a));O(this.K,"end",x(this.gh,this,a));this.K.play(!1)}};p.eh=function(a){var b=this.W;b.style.marginTop=a.y-b.offsetHeight+"px"};
p.fh=function(a){this.dispatchEvent(new lf("a",this,a))};p.gh=function(a){a&&(this.W.style.marginTop="0");dd(this.K);this.Je(a);this.K=null;a||(this.vb.style.display=n);this.dispatchEvent(new lf("toggle",this,a));this.dispatchEvent(new lf("b",this,a))};var nf=null;var W=new Ge;v("BLOG_CMT_OpenIdIdentityFactory",He,void 0);v("BLOG_CMT_LoggedInGaiaIdentity",ze,void 0);v("BLOG_CMT_NotLoggedInGaiaIdentityFactory",Ce,void 0);v("BLOG_CMT_GenericOpenIdIdentityFactory",Ke,void 0);v("BLOG_CMT_NameUrlIdentityFactory",Fe,void 0);v("BLOG_CMT_AnonymousIdentityFactory",Gd,void 0);v("BLOG_CMT_onPost",function(){Ne();return W.sh()},void 0);v("BLOG_CMT_onPreview",function(){return W.th()},void 0);v("BLOG_CMT_onCommentBodyChange",function(){},void 0);
v("BLOG_CMT_onCancel",function(){return W.jh()},void 0);v("BLOG_CMT_onSelectorChange",function(){return W.Jc()},void 0);v("BLOG_CMT_onContinue",function(){return W.kh()},void 0);v("BLOG_CMT_onEdit",function(){return W.mh()},void 0);v("BLOG_CMT_addIdentity",function(a){return W.hc(a)},void 0);v("BLOG_CMT_addAndSelectIdentity",function(a){return W.rd(a)},void 0);v("BLOG_CMT_addIdentityFactory",function(a){return W.la(a)},void 0);v("BLOG_CMT_addNameUrlIdentityFactory",function(){return W.Qf()},void 0);
v("BLOG_CMT_addAnonIdentity",function(){return W.Pf()},void 0);v("BLOG_CMT_addNotLoggedInGaiaIdentity",function(){return W.Rf()},void 0);v("BLOG_CMT_init",function(a,b){he(document.location.href);W.Dh();W.Jc();W.le();xe(a,b);J(Ja).value==Oa&&(J(Ja).value="false",oe(J(da),"previewMode"));ge();return!0},void 0);
v("BLOG_CMT_addOpenIdIdentityFactories",function(){W.la(new He("LJ","http://{username}.livejournal.com","LiveJournal","LiveJournal username:"));W.la(new He("WP","http://{username}.wordpress.com","WordPress","WordPress username:"));W.la(new He("TP","https://profile.typepad.com/{username}","TypePad","TypePad username:"));W.la(new He("AIM","http://openid.aol.com/{username}","AIM","AIM username:"));W.la(new Ke)},void 0);v("BLOG_CMT_createPhotoZippy",function(a,b){J(a)&&J(b)&&(nf=new mf(a,b))},void 0);
v("BLOG_CMT_closePhotoZippy",function(){null!=nf&&nf.collapse()},void 0);v("BLOG_CMT_finalizeBG",function(){window.wd&&window.wd.invoke(function(a){document.getElementById(fa).value=a})},void 0);
v("BLOG_CMT_getBG",function(){var a=new Hd("/comment-iframe-bg.g"),b=document.getElementById(fa).value;b&&a.Ub(fa,b);b=null;"Microsoft Internet Explorer"==window.navigator.appName&&(document.documentMode?b=document.documentMode:(b=5,document.compatMode&&"CSS1Compat"==document.compatMode&&(b=7)));b&&a.Ub("iemode",b);document.getElementById("pageID")&&a.Ub("page","1");Rd&&a.Ub("bgint",Rd);yd(a,function(){if(this.ab()){var a=eval(this.ug());a instanceof Object&&a.length&&(1<a.length&&(eval(a[1]),Rd=
a[2]),window.wd=new botguard.bg(a[0]))}})},void 0);v("BLOG_CMT_setBG",function(a){Rd=a},void 0);v("BLOG_CMT_subscription.toggle",function(){if(!ue){ue=!0;var a=J("commentSubscriptionForm");yd(a.action,function(){ue=!1;if(this.ab()){var a=this.Td();null!=a.errorMessage?V(3,a.errorMessage,!0):le(a.statusMessage);xe(a.can_subscribe,a.is_subscribed)}else V(3,"An error occurred while contacting the server.",!0)},"POST",te(a))}},void 0);v("BLOG_CMT_showStatusMessage",le,void 0);
v("BLOG_CMT_showPostErrorMessage",function(a){V(4,a,!0)},void 0);v("BLOG_CMT_hidePreview",function(){Ne();W.gb();fe()},void 0);v("BLOG_xhr",Q,void 0);Q.send=yd;Q.prototype.isSuccess=Q.prototype.ab;Q.prototype.getResponseJson=Q.prototype.Td;v("$",J,void 0);function of(a){return function(b){var c=-1;try{c=b.status}catch(d){}return 500<=c?(b.responseText.length?document.body.innerHTML=b.responseText:window.alert(LayoutsMessages.SERVER_ERROR),!1):a?a(b):!0}};var qf=function(a,b,c){var d=a.ownerDocument;b=b._GetHelper();var f=b._GetData(),g=c._GetAllData();a=pf(d,a,h,"widget-wrap1");a=pf(d,a,h,"widget-wrap2");a=pf(d,a,h,"widget-wrap3");var k=pf(d,a,h,"widget-content");if(a=f.version&&1<f.version)k.className+=" visibility",pf(d,k,h,"layout-widget-state "+(f.isVisible?"visible":"not-visible")).setAttribute("title",f.visibilityTooltipMessage);var l=pf(d,k,h,"layout-title");if(f[wa]){var q=pf(d,k,h,va);q.appendChild(d.createTextNode(f[wa]));q.setAttribute("title",
f[va])}l.appendChild(d.createTextNode(f["layout-title"]));f=pf(d,k,"a","editlink");var ba=b._GenerateWidgetMetadata();f.setAttribute("href",ba.quickEditUrl);f.target=ha;f.onclick=function(){return c._PopupConfig(d.getElementById(ba.instanceId))};a&&(f.className+=" icon");f.appendChild(d.createTextNode(g.messages.edit||"Edit"))},pf=function(a,b,c,d){a=a.createElement(c);a.className=d;b.appendChild(a);return a};var rf=function(){this.zh={};this.ne={};this.Mc={};this.Ze=null;this.we=[]};Za(rf);rf.prototype.Od=function(a,b){return a+"_"+b+".js"};var sf=function(a){eval(a)};rf.prototype.Zd=function(a,b){v("__gjsload__",sf,void 0);this.Ze=a.replace(/\.js$/,"");b&&(this.Od=b);xb(this.we,function(a){this.Wg(a)},this);Db(this.we)};rf.prototype.Bh=function(a,b,c){var d=this.ne,f=this.zh;d[a]||(d[a]={});if(c)d[a][b]=c;else if(f[a]){for(b=0;b<f[a].length;++b)(0,f[a][b][1])(d[a][f[a][b][0]]);delete f[a];delete this.Mc[a]}};
rf.prototype.Wg=function(a){sd(function(){if(!this.ne[a]){var b=this.Od(this.Ze,a),c=Nb(this.Mc,b);this.Mc[a]=b;c||(b=Dc("SCRIPT",{type:"text/javascript",src:b}),document.body.appendChild(b))}},0,this)};var tf=function(){this.L=[];this.R=[]};p=tf.prototype;p.Xg=function(){0==this.L.length&&(this.L=this.R,this.L.reverse(),this.R=[])};p.enqueue=function(a){this.R.push(a)};p.dequeue=function(){this.Xg();return this.L.pop()};p.s=function(){return this.L.length+this.R.length};p.isEmpty=function(){return 0==this.L.length&&0==this.R.length};p.clear=function(){this.L=[];this.R=[]};p.contains=function(a){return A(this.L,a)||A(this.R,a)};
p.remove=function(a){var b=this.L;var c=wb(b,a);0<=c?(Array.prototype.splice.call(b,c,1),b=!0):b=!1;return b||Eb(this.R,a)};p.u=function(){for(var a=[],b=this.L.length-1;0<=b;--b)a.push(this.L[b]);var c=this.R.length;for(b=0;b<c;++b)a.push(this.R[b]);return a};var uf=function(a){this.l=new od;a&&this.addAll(a)},vf=function(a){var b=typeof a;return b==Aa&&a||b==m?"o"+(a[db]||(a[db]=++eb)):b.substr(0,1)+a};p=uf.prototype;p.s=function(){return this.l.s()};p.add=function(a){this.l.set(vf(a),a)};p.addAll=function(a){a=qd(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};p.Rb=function(a){a=qd(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};p.remove=function(a){return this.l.remove(vf(a))};p.clear=function(){this.l.clear()};p.isEmpty=function(){return this.l.isEmpty()};
p.contains=function(a){return this.l.ma(vf(a))};p.u=function(){return this.l.u()};p.clone=function(){return new uf(this)};p.fc=function(){return this.l.fc(!1)};var wf=function(a,b){K.call(this);this.me=a||0;this.Ob=b||10;if(this.me>this.Ob)throw Error("[goog.structs.Pool] Min can not be greater than max");this.Y=new tf;this.ga=new uf;this.delay=0;this.Cc=null;this.ob()};y(wf,K);p=wf.prototype;p.yb=function(){var a=hb();if(!(null!=this.Cc&&a-this.Cc<this.delay)){var b=this.Ch();b&&(this.Cc=a,this.ga.add(b));return b}};p.Sc=function(a){return this.ga.remove(a)?(this.gc(a),!0):!1};
p.Ch=function(){for(var a;0<this.Nd()&&(a=this.Y.dequeue(),!this.Ic(a));)this.ob();!a&&this.s()<this.Ob&&(a=this.nc());return a};p.gc=function(a){this.ga.remove(a);this.Ic(a)&&this.s()<this.Ob?this.Y.enqueue(a):this.pc(a)};p.ob=function(){for(var a=this.Y;this.s()<this.me;)a.enqueue(this.nc());for(;this.s()>this.Ob&&0<this.Nd();)this.pc(a.dequeue())};p.nc=function(){return{}};p.pc=function(a){if(typeof a.na==m)a.na();else for(var b in a)a[b]=null};p.Ic=function(a){return typeof a.Xf==m?a.Xf():!0};
p.contains=function(a){return this.Y.contains(a)||this.ga.contains(a)};p.s=function(){return this.Y.s()+this.ga.s()};p.pg=function(){return this.ga.s()};p.Nd=function(){return this.Y.s()};p.isEmpty=function(){return this.Y.isEmpty()&&this.ga.isEmpty()};p.i=function(){wf.h.i.call(this);if(0<this.pg())throw Error("[goog.structs.Pool] Objects not released");delete this.ga;for(var a=this.Y;!a.isEmpty();)this.pc(a.dequeue());delete this.Y};var xf=function(a,b){this.ie=a;this.bd=b};xf.prototype.getKey=function(){return this.ie};xf.prototype.clone=function(){return new xf(this.ie,this.bd)};var yf=function(a){this.O=[];a&&this.Mg(a)};p=yf.prototype;p.ae=function(a,b){var c=this.O;c.push(new xf(a,b));this.bh(c.length-1)};p.Mg=function(a){if(a instanceof yf){var b=a.M();a=a.u();if(0>=this.s()){for(var c=this.O,d=0;d<b.length;d++)c.push(new xf(b[d],a[d]));return}}else b=Mb(a),a=Lb(a);for(d=0;d<b.length;d++)this.ae(b[d],a[d])};p.remove=function(){var a=this.O,b=a.length,c=a[0];if(!(0>=b))return 1==b?Db(a):(a[0]=a.pop(),this.Zg(0)),c.bd};
p.Zg=function(a){for(var b=this.O,c=b.length,d=b[a];a<c>>1;){var f=this.sg(a),g=this.wg(a);f=g<c&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>d.getKey())break;b[a]=b[f];a=f}b[a]=d};p.bh=function(a){for(var b=this.O,c=b[a];0<a;){var d=this.tg(a);if(b[d].getKey()>c.getKey())b[a]=b[d],a=d;else break}b[a]=c};p.sg=function(a){return 2*a+1};p.wg=function(a){return 2*a+2};p.tg=function(a){return a-1>>1};p.u=function(){for(var a=this.O,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].bd);return b};
p.M=function(){for(var a=this.O,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};p.ma=function(a){return Bb(this.O,function(b){return b.getKey()==a})};p.clone=function(){return new yf(this)};p.s=function(){return this.O.length};p.isEmpty=function(){return 0==this.O.length};p.clear=function(){Db(this.O)};var zf=function(){yf.call(this)};y(zf,yf);zf.prototype.enqueue=function(a,b){this.ae(a,b)};zf.prototype.dequeue=function(){return this.remove()};var Af=function(a,b){this.Fd=void 0;this.Sb=new zf;wf.call(this,a,b)};y(Af,wf);p=Af.prototype;p.yb=function(a,b){if(!a)return(a=Af.h.yb.call(this))&&this.delay&&(this.Fd=r.setTimeout(x(this.Ab,this),this.delay)),a;this.Sb.enqueue(t(b)?b:100,a);this.Ab()};p.Ab=function(){for(var a=this.Sb;0<a.s();){var b=this.yb();if(b)a.dequeue().apply(this,[b]);else break}};p.gc=function(a){Af.h.gc.call(this,a);this.Ab()};p.ob=function(){Af.h.ob.call(this);this.Ab()};
p.i=function(){Af.h.i.call(this);r.clearTimeout(this.Fd);this.Sb.clear();this.Sb=null};var Bf=function(a,b,c,d){this.uc=a;this.aa=!!d;Af.call(this,b,c)};y(Bf,Af);Bf.prototype.nc=function(){var a=new Q,b=this.uc;b&&b.forEach(function(b,d){a.headers.set(d,b)});this.aa&&a.Vc(!0);return a};Bf.prototype.Ic=function(a){return!a.wa&&!a.Gb()};var Cf=function(a,b,c,d,f,g){P.call(this);this.Hc=t(a)?a:1;this.ua=t(f)?Math.max(0,f):0;this.aa=!!g;this.La=new Bf(b,c,d,g);this.P=new od;this.wb=new Qe(this)};y(Cf,P);var Df=[Fa,e,Na,"error","abort","timeout"];p=Cf.prototype;p.Uc=function(a){this.ua=Math.max(0,a)};p.send=function(a,b,c,d,f,g,k,l,q,ba){if(this.P.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new Ef(b,x(this.Dg,this,a),c,d,f,k,t(l)?l:this.Hc,q,t(ba)?ba:this.aa);this.P.set(a,b);a=x(this.Ag,this,a);this.La.yb(a,g);return b};
p.abort=function(a,b){var c=this.P.get(a);if(c){var d=c.Yb;c.Fh(!0);b&&(d&&(this.Ae(d,c.cd),Vc(d,Fa,function(){this.La.Sc(d)},!1,this)),this.P.remove(a));d&&d.abort()}};p.Ag=function(a,b){var c=this.P.get(a);c&&!c.Yb?(this.Sf(b,c.cd),b.Uc(this.ua),b.Ih(c.Ia),b.Vc(c.aa),c.Yb=b,this.dispatchEvent(new Ff(Fa,this,a,b)),this.De(a,b),c.pd&&b.abort()):this.La.Sc(b)};
p.Dg=function(a,b){var c=b.target;switch(b.type){case Fa:this.De(a,c);break;case e:return this.Bg(a,c,b);case Na:this.Gg(a,c);break;case "timeout":case "error":this.Cg(a,c);break;case "abort":this.zg(a,c)}return null};p.De=function(a,b){var c=this.P.get(a);!c||c.Bd||c.tc()?(c&&(this.Ae(b,c.cd),this.P.remove(a)),this.La.Sc(b)):(c.Lg(),b.send(c.getUrl(),c.Yg,c.getContent(),c.uc))};
p.Bg=function(a,b,c){var d=this.P.get(a);if(7==b.Fa||b.ab()||d.tc())if(this.dispatchEvent(new Ff(e,this,a,b)),d&&(d.Gh(!0),d.Ad))return d.Ad.call(b,c);return null};p.zg=function(a,b){this.dispatchEvent(new Ff("abort",this,a,b))};p.Gg=function(a,b){this.dispatchEvent(new Ff(Na,this,a,b))};p.Cg=function(a,b){this.P.get(a).tc()&&this.dispatchEvent(new Ff("error",this,a,b))};p.Ae=function(a,b,c){this.wb.Wb(a,c||Df,b)};p.Sf=function(a,b,c){this.wb.Ga(a,c||Df,b)};
p.i=function(){Cf.h.i.call(this);this.La.na();this.La=null;this.wb.na();this.wb=null;this.P.clear();this.P=null};var Ff=function(a,b,c,d){L.call(this,a,b);this.id=c;this.Yb=d};y(Ff,L);var Ef=function(a,b,c,d,f,g,k,l,q){this.Nh=a;this.Yg=c||"GET";this.ag=d;this.uc=f||null;this.Hc=t(k)?k:1;this.vd=0;this.pd=this.Bd=!1;this.cd=b;this.Ad=g;this.Ia=l||"";this.aa=!!q;this.Yb=null};p=Ef.prototype;p.getUrl=function(){return this.Nh};p.getContent=function(){return this.ag};p.Lg=function(){this.vd++};
p.tc=function(){return this.vd>this.Hc};p.Gh=function(a){this.Bd=a};p.Fh=function(a){this.pd=a};function Gf(a,b,c,d,f,g){this.Za=a;this.Ge=b;this.Fe=d||null;this.data=f||null;if(g){if(this.oc=g,"displayModeSnippet"!=g&&"displayModeFull"!=g&&g!=ja&&g!=ka)throw"bad display mode: "+g;}else this.oc=ka;this.Hb=!1}Gf.prototype.rg=function(){return this.Za};function Hf(a){this.gg=!0;this.C=a;this.Xb=null}p=Hf.prototype;p.Jf=function(a){this.Xb=a};p.jf=function(){return this.C.data};p.Ef=function(a){return this.C.data=a};p.Gf=function(a){return this.C.Hb=a};
p.ff=function(){var a={};a.type=this.Xb.Ve;a.instanceId=this.C.Za;a.sectionId=this.C.Ge;a.actionUrl=X.kc;a.quickEditUrl=X.Jd+"&widgetType="+this.Xb.Ve+"&widgetId="+this.C.Za+"&sectionId="+this.C.Ge+"&action="+X.fd;return a};p.ec=function(a,b,c,d){b=b||{};window.__wavt&&(b.xssi_token=window.__wavt);X.ec(a,b,this.C.Za,this.Xb.Ve,c,d)};function X(){}X.nf=function(a,b,c){X.ja={};X.Jd=a;X.kc=b;X.Yh=c;X.Ta={};X.Zb=new Cf;X.pe=0;X.Nc=0;O(X.Zb,Fa,function(){X.Nc++});O(X.Zb,e,function(){X.Nc--})};
X.Lf=function(a){a=X.cf(a.document);document.body.appendChild(a)};X.Kf=function(a){X.Lf(window);if(window.parent==window){var b="Preview";a&&(b=a);a=X.bf(window.document,b);document.body.appendChild(a[0]);document.body.appendChild(a[1])}};X.qf=ha;X.af=ha;X.fd="editWidget";X.hf=function(){return X.kc};X.Hf=function(a,b){X.Kc=a;X.yh=b};X.lf=function(){return X.Kc};X.If=function(a){X.Qh=a};X.gd=function(){return X.Qh};X.Ff=function(a){X.Ta=a};
X.gf=function(){var a={},b;for(b in X.Ta){var c=X.Ta[b];a[c.name]=c.data}c={};for(b in X.ja)c[b]=X.ja[b].B.C.data;a.widgets=c;return a};X.jd=function(a,b){var c=new Hf(b);a=new window[a](c);c.Jf(a);X.ja[b.Za]=a;X.ed(a);return a};X.wf=function(a,b){a=X.jd(a,b);a.B.Gf(!0);return a};X.ed=function(a){a.B.C.oc!=ka&&(a.B.gg=!1)};X.va=function(a){return X.ja?X.ja[a]:null};
X.dc=function(a,b,c,d,f){var g="";d&&(g="&widgetId="+d);a=X.Jd+"&action="+a+"&sectionId="+b+"&widgetType="+c+g;if(window.name==f)return window.location.replace(a),window.focus(),window;f=window.open(a,f,"width=570,height=600,left=75,top=20,resizable=yes,scrollbars=yes");f.focus();return f};
X.uf=function(a){var b=a.getAttribute("id"),c=X.va(b);if(c){var d=c.B.Oa;if(null!=d&&!d.closed)return d.focus(),!1}d="config"+b;a=X.dc(X.fd,a.parentNode.getAttribute("id"),a.getAttribute("widgetType"),b,d);c&&(c.B.Oa=a);return!1};X.vf=function(a){X.dc(X.af,a.parentNode.getAttribute("id"),a.getAttribute("widgetType"),a.getAttribute("id"),X.qf);return!1};X.df=function(a,b,c){X.ka(c,c.LayoutsMessages.DELETING);X.ld("delete",{},a,b)};
Hf.prototype.Bf=function(a,b){X.ka(b,b.LayoutsMessages.SAVING);this.ec("configure",a)};X.Cf=function(a,b,c){a.sectionid=document.getElementById("sectionId").value;X.ka(c,c.LayoutsMessages.SAVING);X.ld("addnew",a,"",b)};X.Th=function(a,b,c){b=X.va(b);b.B.C.Hb?X.Cf(a,c,window):b.B.Bf(a,window)};X.ec=function(a,b,c,d,f,g){X.kd(X.kc,a,b,c,d,f,g)};X.ld=function(a,b,c,d,f){X.Kc&&(b.security_token=X.yh,X.kd(X.Kc,a,b,c,d,f))};
X.kd=function(a,b,c,d,f,g,k){b=["action="+encodeURIComponent(b),"widgetId="+encodeURIComponent(d),"widgetType="+encodeURIComponent(f),"responseType=js"];for(var l in c)if(typeof c[l]==Aa)for(d=c[l],f=0;f<d.length;++f)b.push(encodeURIComponent(l)+"="+encodeURIComponent(d[f]));else b.push(encodeURIComponent(l)+"="+encodeURIComponent(c[l]));var q=g||of();c=function(){q(this.a)&&window.eval(this.vg())};"GET"==k?(a=0<=a.indexOf("?")?a+"&":a+"?",X.Zb.send(""+X.pe++,a+b.join("&"),"GET",void 0,null,null,
c)):X.Zb.send(""+X.pe++,a,"POST",b.join("&"),null,null,c)};X.Df=function(a,b){a&&(a=X.va(a))&&(a.B.Oa=b)};X.mb=function(a,b){0==X.Nc?a.setTimeout(function(){a.close()},b):a.setTimeout(function(){X.mb(a,b)},200)};X.pf=function(a,b){a&&(X.mb(a,100),X.Mf(a,b))};X.Mf=function(a,b){if(a){var c=a.document.getElementById(La);c&&(c=c.innerHTML);c&&a&&a.opener.parent&&a.opener.parent.editor&&a.opener.parent.editor.SetSaveMessage(c,b)}};
X.hd=function(a,b,c){a=X.ja[a];if(null!=c.errors){var d=a?a.B.Oa:null;d||(d=window);X.ka(d,c.errors);a&&a.nb?a.nb(b,c,d):X.nb(c,d)}else a.hd(b,c)};X.nb=function(a,b){a=a["error-details"];for(var c in a)If(c,a[c],b.document)};X.rf=function(a,b){window.parent&&window.parent.editor&&b?X.sf(a,b):window.location.replace(window.location.href)};X.sf=function(a,b){var c=X.va(a);c.B.Ef(b.data);a=document.getElementById(a);Gc(a);qf(a,c,X);c.B.Oa=null};
X.mf=function(a,b,c){var d=c[Ka];if(null!=c.errors)X.ka(window,c.errors),X.nb(c,window);else if("addnew"==b){if(X.bc(window)){if(window.opener&&window.opener.parent)var f=window.opener.parent;f&&f.editor&&f.editor.HandleAddNewWidget(c)}X.ka(window,d);null==window.opener?window.location="/rearrange?blogID="+c.blogID:f&&f._WidgetManager?f._WidgetManager._KillPopupDelay(window):X.mb(window,100)}else c=X.ja[a],"delete"==b&&(X.ka(c.B.Oa,d),X.ef(a,"_OnWidgetDeleted"))};
X.tf=function(a){var b=X.va(a);b&&(b.B.C.oc==ja?top.editor.HandleDeleteWidget(b.B.C.Fe):(b=b.B.C.Fe,b.parentNode.removeChild(b)),delete X.ja[a])};X.ef=function(a,b,c){if(X.bc(window)){var d=window.opener;c||(c=d._WidgetManager[b]);c(a);d._WidgetManager?d._WidgetManager._KillPopupDelay(window,a):X.mb(window,100)}else a=X.gd()+"?widgetId="+a,a+="&func="+encodeURIComponent(b),window.location.replace(a)};X.bc=function(a){var b=!1;try{if(a.opener){var c="X"+a.opener.document.domain;c&&"X"!=c&&(b=!0)}}catch(d){}return b};
X.md="status-msg-yellow-on-white";X.ka=function(a,b){a||(a=self);var c=a.document.getElementById(La);c&&(c.innerHTML=b);(a=a.document.getElementById(Ka))&&oe(a,X.md)};X.Rh=function(a){a||(a=self);(a=a.document.getElementById(Ka))&&qe(a,X.md)};X.Sh=function(a){a&&0<a.length&&"http"!=a.substring(0,4)&&(a="http://"+a);return a};X.kf=function(a,b){if(A(ne(a),b))return a;if(a)for(var c=a.childNodes.length,d=0;d<c;d++){var f=X.kf(a.childNodes.item(d),b);if(f)return f}return null};
X.cf=function(a){a=a.createElement(h);a.className="blogger-clickTrap singleton-element";a.style.position="fixed";a.style.top="0";a.style.left="0";a.style.width="100%";a.style.height="100%";C&&!H(7)&&(a.style.height="expression(this.parentNode.clientHeight)");a.style.zIndex="1000";a.style.cursor="default";a.onclick=X.cc;a.onmousedown=X.cc;a.onmouseup=X.cc;a.style.background="white";a.style.filter="alpha(opacity=1)";a.style.opacity=".01";a.innerHTML="&nbsp;";return a};
X.bf=function(a,b){var c=X.dd(a,b);a=X.dd(a,b);c.style.backgroundColor="#000";c.style.border="1px solid #aaa";C&&(c.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678) alpha(opacity=50)');c.style.opacity=".5";a.style.border="1px solid transparent";c.style.zIndex=1200;a.style.zIndex=1200;return[c,a]};
X.dd=function(a,b){a=a.createElement(h);a.style.position="absolute";a.style.top="75px";a.style.left="-225px";a.style.width="600px";a.style.height="28px";a.style.margin="0";a.style.padding="10px";a.style.fontSize="24px";a.style.textAlign="center";a.style.color="#fff";a.style.fontFamily='"trebuchet ms",verdana,arial,sans-serif';C&&(a.style.top="-140px",a.style.left="-140px",a.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)');
a.style.MozTransform=Ga;a.style.MozTransformOrigin="50% 0";a.style.WebkitTransform=Ga;a.style.WebkitTransformOrigin="50% 0";a.innerHTML=b;a.className="singleton-element";return a};X.Wh=function(a){for(var b in X.Ta){var c=X.Ta[b];if(c&&"features"==c.name)return c.data[a]==Oa}return!1};X.cc=function(a){a||(a=window.event);a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation());return!1};
var Jf=function(a,b){b||(b=document);return b.getElementById("errormessage_"+a)},Kf=function(a){if(a=Jf(a))Gc(a),a.className="errorbox-good"},If=function(a,b,c){if(a=Jf(a,c))a.innerHTML=b,a.className="errorbox-bad errormsg"};v("_WidgetManager",X,void 0);X._Init=X.nf;X._SetPageActionUrl=X.Hf;X._GetPageActionUrl=X.lf;X._SetWidgetRefreshUrl=X.If;X._GetWidgetRefreshUrl=X.gd;X._GetCallbackUrl=X.hf;X._DeleteWidgetFromPage=X.df;X._DisplayWidget=X.ed;X._GetWidget=X.va;X._HandleControllerResult=X.hd;
X._HandlePageActionResult=X.mf;X._IsOpenerReachable=X.bc;X._SetConfigWin=X.Df;X._SetDataContext=X.Ff;X._SetupPreview=X.Kf;X._RegisterWidget=X.jd;X._RegisterNewWidget=X.wf;X._PopupPaneFromParams=X.dc;X._PopupConfig=X.uf;X._PopupToolbox=X.vf;X._KillPopupDelay=X.pf;X._OnWidgetConfigured=X.rf;X._OnWidgetDeleted=X.tf;v("_WidgetInfo",Gf,void 0);Gf.prototype._getInstanceId=Gf.prototype.rg;Hf.prototype._GetData=Hf.prototype.jf;Hf.prototype._GenerateWidgetMetadata=Hf.prototype.ff;X._GetAllData=X.gf;
v("widget_module_provide",function(a,b,c){rf.qg().Bh(a,b,c)},void 0);function Y(a,b,c,d,f,g,k,l){this.F=a;this.xd="null"!=b?b:null;this.ge=c;this.ee=d;this.fe=f;this.He=g;this.he=k;this.Eh=l;this.Db=this.Da=-1;this.wc=null;this.fb=300;this.Gc="200px";this.J=document.getElementById(this.F+"_picImg");this.rb=document.getElementById(this.F+"_changeImageLink");this.Cb=document.getElementById(this.F+"_imageChoiceTable");this.xc=document.getElementById(this.F+"_imgSrcFromPCRadio");this.Yd=document.getElementById(this.F+"_imgSrcFromWebRadio");this.f=document.getElementById(this.F+
"_imgFileNameInput");this.Va=document.getElementById(this.F+"_imgUrlTextInput");this.td=window.frames[this.F+"_asynchronousFileUploadIframe"];this.vc=0;this.v=new Image;this.v.onload=x(this.xh,this);this.v.onerror=x(this.nh,this);this.Ld=!1;this.za=this.w=this.Lb=null;this.Rc=!1}p=Y.prototype;
p.xh=function(){this.vc=0;Kf(this.F+ca);Kf(this.F+aa);this.xc.checked&&0!=this.Da||(this.Da=this.v.width,this.Db=this.v.height,this.wc=this.v.src);var a=1,b=1;this.v.width>this.fb&&(a=this.fb/this.v.width);this.v.height>this.fb&&(b=this.fb/this.v.height);a=Math.min(a,b);this.J.style.width=Math.round(this.v.width*a)+"px";this.J.style.height=Math.round(this.v.height*a)+"px";this.J.src=this.v.src;this.J.style.display="";this.Cb.style.display=n;this.rb.style.display="";this.f.disabled=!0;this.ge&&this.ge.call({},
this.J.src,this.wc,this.Da,this.Db)};p.ib=function(a,b,c,d){a?(If(this.F+aa,b),Kf(this.F+ca)):(If(this.F+ca,b),Kf(this.F+aa));this.J.style.display=n;this.Cb.style.display="";this.rb.style.display=n;this.f.disabled=!1;this.ee&&this.ee.call({},c,d)};p.nh=function(){if(2>this.vc){this.vc++;var a=this.v.src;this.v.src="";this.bb(a)}else this.ib(this.xc.checked,WidgetMessages.SIV_INVALID_URL,this.J.src,[])};p.bb=function(a){this.Te();this.v.src=a};
p.Yf=function(a){a=a||window.event;window.event?(a.returnValue=!1,a.cancelBubble=!0):(a.preventDefault(),a.stopPropagation());this.J.style.display=n;this.rb.style.display=n;this.Cb.style.display="";this.f.disabled=!1;this.Va.value="";this.Be();this.Rc=!0;this.fe&&this.fe.call({})};p.Jg=function(){this.xc.checked=Oa;this.Va.value="";this.Te();this.ah();this.Ld=!0;try{this.w.submit()}catch(a){this.ib(!0,WidgetMessages.SIV_INVALID_URL,this.w.value,[])}this.$g()};
p.lc=function(){var a=this.td.document.result;if(a)if(a.hasErrors)0<a.errors.length?this.ib(!0,a.errors[0].message,this.f.value,a.errors):this.ib(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,a.errors);else{var b=Math.max(a.origWidth,a.origHeight),c=this.Wd();0!=this.Da&&-1!=c&&b>c?(b=c/b,this.Da=Math.round(a.origWidth*b),this.Db=Math.round(a.origHeight*b)):(this.Da=a.origWidth,this.Db=a.origHeight);this.wc=a.mainSrc;this.bb(a.thumbSrc)}else this.ib(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,
[])};p.Kg=function(a){9!=(a||window.event).keyCode&&(this.Yd.checked=Oa,null!=this.Lb&&(window.clearTimeout(this.Lb),this.Lb=null),a=x(this.Tg,this),this.Lb=window.setTimeout(a,1E3))};p.Tg=function(){if(this.Rc||this.v.src!=this.Va.value)this.Be(),this.bb(this.Va.value);this.Rc=!1};p.Vg=function(a){this.Yd.checked=!0;this.Va.value=a;this.bb(a)};
p.Te=function(){this.J.src="https://resources.blogblog.com/img/icon_inprogress.gif";this.J.style.width=this.Gc;this.J.style.height=this.Gc;this.J.style.display="";this.Cb.style.display=n;this.rb.style.display=n};
p.ah=function(){if(!this.w){this.w=document.createElement("form");this.w.action="imageUpload.do";this.w.method="POST";this.w.target=this.td.name;this.w.encoding="multipart/form-data";this.w.style.display=n;if(this.xd){var a=document.createElement(ta);a.type=pa;a.name="blogID";a.value=this.xd;this.w.appendChild(a)}a=document.createElement(ta);a.type=pa;a.name=Ha;a.id=Ha;this.w.appendChild(a);a=document.createElement(ta);a.type=pa;a.name="security_token";a.value=this.Eh;this.w.appendChild(a);document.body.appendChild(this.w)}a=
this.Wd();-1==a&&(a=1600);document.getElementById(Ha).value=a;this.za={parent:this.f.parentNode,nextSibling:this.f.nextSibling};this.f.parentNode.removeChild(this.f);this.w.appendChild(this.f)};p.Hh=function(a){this.fb=a;this.Gc=a+"px"};p.$g=function(){this.w.removeChild(this.f);this.za&&this.za.nextSibling?this.za.parent.insertBefore(this.f,this.za.nextSibling):this.za.parent.appendChild(this.f)};
p.Be=function(){var a=document.createElement(ta);a.type="file";a.name=this.f.name;a.id=this.f.id;a.onchange=this.f.onchange;var b=this.f.nextSibling;null==b?this.f.parentNode.appendChild(a):this.f.parentNode.insertBefore(a,b);this.f.parentNode.removeChild(this.f);this.f=a};p.Wd=function(){return-1==this.He&&this.he?this.he():this.He};function Z(){this.ad={}}var Lf=new Z;Z.prototype.cg=function(a,b,c,d,f,g,k,l){this.ad[a]=new Y(a,b,eval(c),eval(d),eval(f),g,eval(k),l);return this.ad[a]};
Z.prototype.Vd=function(a){return this.ad[a]};Z.prototype.lc=function(a){(a=this.Vd(a))&&a.Ld&&a.lc()};v("_UploadSimpleImage",Lf,void 0);Z.prototype._createUsiContainer=Z.prototype.cg;Z.prototype._getUsiContainer=Z.prototype.Vd;Z.prototype._channelResultArrived=Z.prototype.lc;Y.prototype._changeImage=Y.prototype.Yf;Y.prototype._imgUrlFileOnChange=Y.prototype.Jg;Y.prototype._imgUrlTextOnKeyUp=Y.prototype.Kg;Y.prototype._loadInitialUrl=Y.prototype.Vg;Y.prototype._loadImageFromUrl=Y.prototype.bb;
Y.prototype._setPreviewSize=Y.prototype.Hh;}).call(this);
